<template><div><h1 id="阿里巴巴java开发手册-第2版" tabindex="-1"><a class="header-anchor" href="#阿里巴巴java开发手册-第2版" aria-hidden="true">#</a> 阿里巴巴Java开发手册（第2版）</h1>
<p>杨冠宝</p>
<h3 id="◆-1-1-命名风格" tabindex="-1"><a class="header-anchor" href="#◆-1-1-命名风格" aria-hidden="true">#</a> ◆ 1.1 命名风格</h3>
<blockquote>
<blockquote>
<p>定义为基本数据类型Boolean isDeleted的属性，它的方法也是isDeleted()，框架在反向解析的时候，“误以为”对应的属性名称是deleted，导致获取不到属性，进而抛出异常。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如果模块、接口、类和方法使用了设计模式，在命名时需体现出具体模式。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-4-oop规约" tabindex="-1"><a class="header-anchor" href="#◆-1-4-oop规约" aria-hidden="true">#</a> ◆ 1.4 OOP规约</h3>
<blockquote>
<blockquote>
<p>避免通过一个类的对象引用访问此类的静态变量或静态方法，造成编译器解析成本无谓增加，直接用类名访问即可。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>所有的覆写方法都必须加@Override注解。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：getObject()与get0bject()的问题。一个是字母的O，一个是数字的0，加@Override注解可以准确判断是否覆盖成功。另外，如果在抽象类中对方法签名进行修改，其实现类会马上编译报错。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对外部正在调用或者二方库依赖的接口，不允许修改方法签名，避免对接口调用方产生影响。若接口过时，则必须加@Deprecated注解，并清晰地说明采用的新接口或者新服务是什么</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Object的equals方法容易抛空指针异常，应使用常量或确定有值的对象调用equals。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>所有整型包装类对象之间值的比较，全部使用equals方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>浮点数之间的等值判断，基本数据类型不能用==进行比较，包装数据类型不能用equals方法判断。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>浮点数采用“尾数+阶码”的编码方式，类似于科学计数法的“有效数字+指数”的表示方式。二进制无法精确表示大部分十进制小数</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在循环体内，字符串的连接方式使用StringBuilder的append方法扩展。说明：下例中，反编译出的字节码文件显示每次循环都会new出一个StringBuilder对象，然后进行append操作，最后通过toString方法返回String对象，造成内存资源浪费。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>final可以声明类、成员变量、方法及本地变量，下列情况使用final关键字。1）不允许被继承的类，如：String类。2）不允许修改引用的域对象，如：POJO类的域变量。3）不允许被覆写的方法，如：POJO类的setter方法。4）不允许在运行过程中给局部变量重新赋值。5）避免上下文重复使用一个变量，使用final描述可以强制重新定义一个变量，方便更好地重构。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>慎用Object的clone方法拷贝对象。说明：对象的clone方法默认是浅拷贝，若想实现深拷贝，需要覆写clone方法来实现域对象的深度遍历式拷贝。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-5-日期时间" tabindex="-1"><a class="header-anchor" href="#◆-1-5-日期时间" aria-hidden="true">#</a> ◆ 1.5 日期时间</h3>
<blockquote>
<blockquote>
<p>说明：在日期格式化时，yyyy表示当天所在的年，大写的YYYY表示week in which year（JDK 7之后引入的概念），意思是当天所在的周属于的年份。一周从周日开始，周六结束，只要本周跨年，返回的YYYY就是下一年。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在日期格式中，分清楚大写的M和小写的m、大写的H和小写的h分别代表的意义。说明：日期格式中的这两对字母表意如下：1）表示月份，用大写的M；2）表示分钟，用小写的m；3）表示24小时制，用大写的H；4）表示12小时制，用小写的h。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>获取当前毫秒数：是System.currentTimeMillis(); 而不是new Date().getTime()。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如果想获取更加精确的纳秒级时间值，则使用System.nanoTime的方式。在JDK 8中，针对统计时间等场景，推荐使用Instant类。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不允许在程序的任何地方使用：1）java.sql.Date；2）java.sql.Time；3）java.sql.Timestamp。说明：第1个不记录时间，getHours()抛出异常；第2个不记录日期，getYear()抛出异常；第3个在构造方法super((time/1000 1000)时，在Timestamp属性fastTime和nanos中分别存储秒和纳秒信息。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：在使用java.util.Date.after(Date)进行时间比较时，当入参是java.sql.Timestamp时，会触发JDK BUG(JDK 9已修复)，在比较时可能导致意外结果。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-6-集合处理" tabindex="-1"><a class="header-anchor" href="#◆-1-6-集合处理" aria-hidden="true">#</a> ◆ 1.6 集合处理</h3>
<blockquote>
<blockquote>
<p>判断所有集合内部的元素是否为空，应使用isEmpty()方法，而不是使用size()==0的方式。说明：在某些集合中，前者的时间复杂度为O(1)，而且可读性更好。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-7-并发处理" tabindex="-1"><a class="header-anchor" href="#◆-1-7-并发处理" aria-hidden="true">#</a> ◆ 1.7 并发处理</h3>
<blockquote>
<blockquote>
<p>获取单例对象需要保证线程安全，其中的方法也要保证线程安全。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>资源驱动类、工具类、单例工厂类都需要注意。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>线程资源必须通过线程池提供，不允许在应用中自行显式创建线程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>使用线程池的好处是减少在创建和销毁线程上消耗的时间及系统资源，解决资源不足的问题。如果不使用线程池，则有可能造成系统创建大量同类线程而导致消耗完内存或者“过度切换”的问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>SimpleDateFormat是线程不安全的类，一般不要定义为static变量，如果定义为static，则必须加锁，或者使用DateUtils工具类。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>必须回收自定义的ThreadLocal变量，尤其在线程池场景下，线程经常会被复用，如果不清理自定义的ThreadLocal变量，则可能会影响后续业务逻辑和造成内存泄露等问题。尽量在代理中使用try-finally块回收。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在高并发场景中，同步调用应该考量锁的性能损耗。能用无锁数据结构，就不要用锁；能锁区块，就不要锁整个方法体；能用对象锁，就不要用类锁。说明：使加锁的代码块工作量尽可能的小，避免在锁代码块中调用RPC方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在对多个资源、数据库表、对象同时加锁时，需要保持一致的加锁顺序，否则可能会造成死锁。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如果线程一需要对表A、B、C依次全部加锁后才可以进行更新操作，那么线程二的加锁顺序也必须是A、B、C，否则可能出现死锁。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在使用阻塞等待获取锁的方式中，必须在try代码块之外，并且在加锁方法与try代码块之间没有任何可能抛出异常的方法调用，避免加锁成功后，在finally中无法解锁。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明二：如果lock方法在try代码块之内，可能由于其他方法抛出异常，导致在finally代码块中，unlock对未加锁的对象尝试解锁，它会调用AQS的try Release方法（取决于具体实现类），抛出Illegal MonitorStateException异常。说明三：在Lock对象的lock方法实现中，可能抛出unchecked异常，产生的后果与说明二相同。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在使用尝试机制获取锁的方式中，进入业务代码块之前，必须先判断当前线程是否持有锁。锁的释放规则与锁的阻塞等待方式相同。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在并发修改同一记录时，为避免更新丢失，需要加锁。要么在应用层加锁，要么在缓存层加锁，要么在数据库层使用乐观锁，使用version作为更新依据。说明：如果每次访问冲突概率小于20%，则推荐使用乐观锁，否则使用悲观锁。乐观锁的重试次数不得小于3次。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于多线程并行处理定时任务的情况，当Timer运行多个TimeTask时，只要其中之一没有捕获抛出的异常，其他任务便会自动终止。如果使用ScheduledExecutorService，则没有这个问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>与资金相关的金融敏感信息，使用悲观锁策略。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>乐观锁在获得锁的同时已经完成了更新操作，校验逻辑容易出现漏洞。另外，乐观锁对冲突的解决策略有较复杂的要求，处理不当容易造成系统压力或数据异常，所以与资金相关的金融敏感信息不建议使用乐观锁更新。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>正例：悲观锁遵循“一锁二判三更新四释放”的原则</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>使用CountDownLatch进行异步转同步操作，每个线程在退出前必须调用countDown方法，线程执行代码注意catch异常，确保countDown方法被执行到，避免主线程无法执行至await方法，直到超时才返回结果。说明：子线程抛出异常堆栈，不能在主线程try-catch到。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>避免Random实例被多线程使用，虽然共享该实例是线程安全的，但会因竞争同一seed导致性能下降。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Random实例包括java.util.Random的实例或者Math. random()的方式。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>volatile解决多线程内存不可见问题。对于一写多读，可以解决变量同步问题；但是对于多写，同样无法解决线程安全问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当容量不够resize时，由于高并发，HashMap可能出现死链，导致CPU飙升，在开发过程中注意规避此风险。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>ThreadLocal对象使用static修饰，Thread Local无法解决共享对象的更新问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这个变量是针对一个线程内所有操作共享的，所以设置为静态变量，所有此类实例共享此静态变量，也就是说，在类第一次被使用时装载，只分配一块存储空间，所有此类的对象（只要是这个线程内定义的）都可以操控这个变量。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-8-控制语句" tabindex="-1"><a class="header-anchor" href="#◆-1-8-控制语句" aria-hidden="true">#</a> ◆ 1.8 控制语句</h3>
<blockquote>
<blockquote>
<p>当switch括号内的变量类型为String并且此变量为外部参数时，必须先进行null判断。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在高并发场景中，避免使用“等于”判断作为中断或退出的条件。说明：如果没有处理好并发控制，容易产生等值判断被“击穿”的情况，使用大于或小于的区间判断条件来代替。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：当判断剩余奖品数量等于0时，终止发放奖品，但因为并发处理错误，导致奖品数量瞬间变成了负数，这样的话活动将无法终止。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>表达异常的分支时，尽量少用if-else方式，这种方式可以改写成：</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：如果不得不使用if()...else if()...else...方式表达逻辑，那么为【强制】避免后续代码维护困难，请勿超过3层。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>公开接口需要进行入参保护，尤其是批量操作的接口。反例：某业务系统，提供一个用户批量查询的接口，API文档上有说最多查多少个，但接口实现上没做任何保护，导致调用方传了一个1000的用户id数组，查询信息后，内存爆满。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于下列情形，需要进行参数校验。1）调用频次低的方法。2）执行时间开销很大的方法。在此情形中，参数校验时间几乎可以忽略不计，但如果因为参数错误导致中间执行回退，或者错误，是得不偿失的。3）需要极高稳定性和可用性的方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4）对外提供的开放接口，不管是否为RPC/API/HTTP接口。5）敏感权限入口。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>下列情形，不需要进行参数校验。1）极有可能被循环调用的方法。但在方法说明里必须注明外部参数检查。2）底层调用频度比较高的方法。像纯净水过滤的最后一道，参数错误不太可能到底层才暴露问题。一般DAO层与Service层都在同一个应用中，部署在同一台服务器中，所以DAO的参数校验可以省略。3）被声明成private且只会被自己代码所调用的方法，如果能够确定调用方法的代码传入参数已经做过检查或者肯定不会有问题，那么此时可以不校验参数。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-10-前后端规约" tabindex="-1"><a class="header-anchor" href="#◆-1-10-前后端规约" aria-hidden="true">#</a> ◆ 1.10 前后端规约</h3>
<blockquote>
<blockquote>
<p>前后端交互的API，需要明确协议、域名、路径、请求方法、请求内容、状态码和响应体。说明：1）协议：生产环境必须使用HTTPS。2）路径：每一个API都需对应一个路径，表示API具体的请求地址。 a）代表一种资源，只能为名词，推荐使用复数，不能为动词，请求方法已经表达动作意义。 b）URL路径不能使用大写，单词如果需要分隔，统一使用下画线。 c）路径禁止携带表示请求内容类型的后缀，比如&quot;.json&quot;,&quot;.xml&quot;，通过accept头表达即可。3）请求方法：对具体操作的定义，常见的请求方法如下。 a）GET：从服务器取出资源。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>b）POST：在服务器新建一个资源。 c）PUT：在服务器更新资源。 d）DELETE：从服务器删除资源。4）请求内容：URL带的参数必须无敏感信息或符合安全要求；body里带参数时必须设置Content-Type。5）响应体：响应体body可放置多种数据类型，由Content-Type头来确定。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当服务端发生错误时，返回给前端的响应信息必须包含HTTP状态码、errorCode、errorMessage和用户提示信息四部分。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>正例：常见的HTTP状态码如下。1）200 OK: 表明该请求被成功地完成，所请求的资源发送到客户端。2）401 Unauthorized: 请求要求身份验证，常见于需要登录而用户未登录的情况。3）403 Forbidden：服务器拒绝请求，常见于机密信息或通过复制其他登录用户链接访问服务器的情况。4）404 Not Found: 服务器无法获得所请求的网页，请求资源不存在。5）500 Internal Server Error: 服务器内部错误。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在前后端交互的JSON格式数据中，所有的key必须都为小写字母开始的lowerCamelCase风格，符合英文表达习惯，且表意完整。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>errorMessage是前后端错误追踪机制的体现，可以在前端输出在type=&quot;hidden&quot;文字类控件中，或者用户端的日志中，帮助我们快速定位问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于需要使用超大整数的场景，服务端一律使用String字符串类型返回，禁止使用Long类型。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：Java服务端如果直接给前端返回Long整型数据，JS会自动转换为Number类型（注：此类型为双精度浮点数，表示原理与取值范围等同于Java中的Double）。Long类型能表示的最大值是263−1，在取值范围之内，当超过253(9007199254740992)的数值转化为JS的Number时，有些数值会有精度损失。扩展说明，在Long取值范围内，任何2的指数次整数都是绝对不会存在精度损失的，所以说精度损失是一个概率问题。若浮点数尾数位与指数位空间不限，则可以精确表示任何整数，但很不幸，双精度浮点数的尾数位只有52位。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：通常在订单号或交易号大于或等于16位时，大概率会出现前后端单据不一致的情况，比如，&quot;orderId&quot;: 362909601374617692，前端拿到的值却是362909601374617660。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当HTTP请求通过URL传递参数时，不能超过2048字节。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：不同浏览器对于URL的最大长度限制略有不同，并且对超出最大长度的处理逻辑也有差异，2048字节是取所有浏览器的最小值。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：某业务将退货的商品id列表放在URL中作为参数传递，当一次退货商品数量过多时，URL参数超长，传递到后端的参数被截断，导致部分商品未能正确退货。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>【强制】HTTP请求通过body传递内容时，必须控制长度，超出最大长度后，后端解析会出错。说明：Nginx默认限制为1MB，Tomcat默认限制为2MB，当确实有业务需要传递较多内容时，可以调大服务器端的限制。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在翻页场景中，如果用户输入的参数少于1，则前端返回第一页参数给后端；如果后端发现用户输入的参数大于最后一页，则直接返回最后一页。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>服务器内部重定向必须使用forward；外部重定向地址必须使用URL统一代理模块，否则会因线上采用HTTPS而导致浏览器提示“不安全”，并且还会带来URL维护不一致的问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>服务器返回信息必须标记是否可以缓存，如果可以缓存，那么客户端可能会重用之前的请求结果。说明：缓存有利于减少交互次数，减少交互的平均延迟。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在接口路径中不要加入版本号，版本控制在HTTP头部信息中体现，有利于向前兼容。说明：当用户在低版本与高版本之间反复切换时，会导致迁移复杂度升高，存在数据错乱的风险。</p>
</blockquote>
</blockquote>
<h3 id="◆-1-11-其他" tabindex="-1"><a class="header-anchor" href="#◆-1-11-其他" aria-hidden="true">#</a> ◆ 1.11 其他</h3>
<blockquote>
<blockquote>
<p>任何数据结构的构造或初始化，都应指定大小，避免数据结构无限增长而耗尽内存。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>8【推荐】及时清理不再使用的代码段或配置信息。说明：对于垃圾代码或过时配置，坚决清理干净，避免程序过度臃肿，代码冗余。</p>
</blockquote>
</blockquote>
<h3 id="◆-2-1-错误码" tabindex="-1"><a class="header-anchor" href="#◆-2-1-错误码" aria-hidden="true">#</a> ◆ 2.1 错误码</h3>
<blockquote>
<blockquote>
<p>当全部正常，但不得不填充错误码时，返回五个零（00000）。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>错误码为字符串类型，共5位，分为错误产生来源、四位数字编号两部分。说明：错误产生来源分为A、B、C三种，A表示错误来源于用户，例如参数错误、用户安装版本过低、用户支付超时等；B表示错误来源于当前系统，例如业务逻辑出错、程序健壮性差等；C表示错误来源于第三方服务，例如CDN服务出错、消息投递超时等；四位数字编号从0001到9999，大类之间的步长间距预留100。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>错误码不能直接输出给用户作为提示信息使用。说明：堆栈、错误码（errorCode）、错误信息(errorMessage)、提示信息（userTip）是一个有效关联并互相转义的和谐整体，但请勿越俎代庖。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>错误码分为一级宏观错误码、二级宏观错误码、三级宏观错误码。说明：在无法确定的错误场景中，可以直接使用一级宏观错误码，分别是：A0001（用户端错误）、B0001（系统执行出错）、C0001（调用第三方服务出错）。</p>
</blockquote>
</blockquote>
<h3 id="◆-2-2-异常处理" tabindex="-1"><a class="header-anchor" href="#◆-2-2-异常处理" aria-hidden="true">#</a> ◆ 2.2 异常处理</h3>
<blockquote>
<blockquote>
<p>2【强制】异常被捕获后不要用来做流程控制和条件控制。说明：异常设计的初衷是解决程序运行中的各种意外，且异常的处理效率比条件判断方式要低很多。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>捕获异常是为了处理异常，不要捕获了却什么都不处理而抛弃之，如果不想处理它，请将该异常抛给它的调用者。最外层的业务使用者必须处理异常，将其转化为用户可以理解的内容。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在事务场景中，抛出异常被catch后，如果需要回滚，那么一定要注意手动回滚事务。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>finally块必须对资源对象、流对象进行关闭操作，如果有异常就要做try-catch操作。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不要在finally块中使用return。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：try块中的return语句执行成功后，并不马上返回，而是继续执行finally块中的语句，如果此处存在return语句，则在此直接返回，无情地丢弃try块中的返回点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在调用RPC、二方包或动态生成类的相关方法时，捕获异常必须使用Throwable类拦截。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>正例：使用JDK 8的Optional类防止产生NPE。</p>
</blockquote>
</blockquote>
<h3 id="◆-2-3-日志规约" tabindex="-1"><a class="header-anchor" href="#◆-2-3-日志规约" aria-hidden="true">#</a> ◆ 2.3 日志规约</h3>
<blockquote>
<blockquote>
<p>所有日志文件至少保存15天，因为有些异常具备以“周”为频次发生的特点。对于当天日志，以“应用名.log”保存在“/home/admin/应用名/logs/”目录下，过往日志格式： {logname}.log.{保存日期}，日期格式：yyyy-MM-dd。[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>根据国家法律，网络运行状态、网络安全事件、个人敏感信息操作等相关记录，留存日志的时间不少于六个月，并且进行网络多机备份。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>应用中的扩展日志（如打点、临时监控、访问日志等）命名方式：appName_logType_logName.log。logType为日志类型，如stats/monitor/access等；logName为日志描述。这种命名的好处是通过文件名就可以知道日志文件属于哪个应用，哪种类型，有什么目的，这也有利于归类查找。说明：推荐对日志进行分类，如将错误日志和业务日志分开存放，既便于开发人员查看，也便于通过日志及时监控系统。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当输出日志时，字符串变量之间的拼接使用占位符的方式。说明：因为String字符串的拼接会使用StringBuilder的append()方式，所以有一定的性能损耗。使用占位符仅是替换动作，可以有效提升性能。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>避免重复打印日志，否则会浪费磁盘空间，务必在日志配置文件中设置additivity=false。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>可以使用warn日志级别记录用户输入参数错误的情况，避免当用户投诉时无所适从。</p>
</blockquote>
</blockquote>
<h2 id="◆-第3章-单元测试" tabindex="-1"><a class="header-anchor" href="#◆-第3章-单元测试" aria-hidden="true">#</a> ◆ 第3章 单元测试</h2>
<blockquote>
<blockquote>
<p>好的单元测试必须遵守AIR原则。说明：单元测试在线上运行时，像空气（AIR）一样感觉不到，但在测试质量的保障方面，却是非常关键的。从宏观上说，好的单元测试具有自动化、独立性、可重复执行的特点。A：Automatic（自动化）；I：Independent（独立性）；R：Repeatable（可重复）。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>单元测试应该是全自动执行的，并且是非交互式的。测试用例通常是被定期执行的，执行过程必须完全自动化才有意义。需要人工检查输出结果的测试不是好的单元测试。单元测试中不准使用System.out进行人肉验证，必须使用assert验证。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>保持单元测试的独立性。为了保证单元测试稳定可靠且便于维护，单元测试用例之间决不能互相调用，也不能依赖执行的先后次序。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：method2需要依赖method1的执行，将执行结果作为method2的输入。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于单元测试，要保证测试粒度足够小，有助于精确定位问题。单元测试粒度至多是类级别，一般是方法级别。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：只有测试粒度足够小，才能在出错时尽快定位到出错位置。单元测试不负责检查跨类或者跨系统的交互逻辑，那是集成测试的领域。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于数据库相关的查询、更新、删除等操作，不能假设数据库里的数据是存在的，或者直接操作数据库把插入数据，请采用程序插入或者导入数据的方式准备数据。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>和数据库相关的单元测试，可以设定自动回滚机制，不给数据库造成脏数据。或者对单元测试产生的数据有明确的前后缀标识。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>为了更方便地进行单元测试，业务代码应避免出现以下情况。1）构造方法中做的事情过多。2）存在过多的全局变量和静态方法。3）存在过多的外部依赖。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4）存在过多的条件语句。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：多层条件语句建议使用卫语句、策略模式、状态模式等方式重构。</p>
</blockquote>
</blockquote>
<h2 id="◆-第4章-安全规约" tabindex="-1"><a class="header-anchor" href="#◆-第4章-安全规约" aria-hidden="true">#</a> ◆ 第4章 安全规约</h2>
<blockquote>
<blockquote>
<p>1【强制】隶属于用户个人的页面或者功能必须进行权限控制校验。说明：防止没有做水平权限校验就可以随意访问、修改、删除别人的数据，比如查看他人的私信内容。2【强制】用户敏感数据禁止直接展示，必须对展示数据进行脱敏。说明：个人手机号码显示为137****0969，隐藏中间4位，防止隐私泄露。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3【强制】用户输入的SQL参数严格使用参数绑定或者METADATA字段值限定，防止SQL注入，禁止字符串拼接SQL访问数据库。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4【强制】用户请求传入的任何参数必须做有效性验证。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：忽略参数校验可能导致如下情况。1）page size过大导致内存溢出。2）恶意order by导致数据库慢查询。3）缓存击穿。4）SSRF。5）任意重定向。6）SQL注入、Shell注入和反序列化注入。7）正则输入源串拒绝服务ReDoS。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Java代码用正则来验证客户端的输入，有些正则写法验证普通用户输入没有问题，但是如果攻击人员使用特殊构造的字符串来验证，则有可能导致死循环。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>5【强制】禁止向HTML页面输出未经安全过滤或未正确转义的用户数据。6【强制】在提交表单、AJAX时须执行CSRF安全验证。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7【强制】URL外部重定向传入的目标地址必须执行白名单过滤。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>8【强制】在使用平台资源时，例如短信、邮件、电话、下单、支付，必须实现正确的防重放的机制，如数量限制、疲劳度控制、验证码校验，避免被滥刷导致用户受扰或平台资损。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：例如，注册时将验证码发送到手机，如果没有限制次数和频率，那么可以利用此功能骚扰其他用户，并造成短信平台资源浪费。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>9【推荐】针对发帖、评论、发送即时消息等用户生成内容的场景，必须实行防刷、文本内容违禁词过滤等风控策略。</p>
</blockquote>
</blockquote>
<h3 id="◆-5-1-建表规约" tabindex="-1"><a class="header-anchor" href="#◆-5-1-建表规约" aria-hidden="true">#</a> ◆ 5.1 建表规约</h3>
<blockquote>
<blockquote>
<p>2【强制】表名、字段名必须使用小写字母或数字，禁止出现数字开头，禁止两个下画线中间只出现数字。数据库字段名的修改代价很大，因为无法进行预发布，所以字段名称需要慎重考虑。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：MySQL在Windows系统中不区分大小写，但在Linux系统中默认区分大小写。因此，数据库名、表名和字段名，都不允许出现任何大写字母，避免节外生枝。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>表名不使用复数名词。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>主键索引名为pk_字段名，唯一索引名为uk_字段名，普通索引名则为idx_字段名。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6【强制】小数类型为decimal，禁止使用float和double类型。说明：在存储时，float和double类型存在精度损失的问题，很可能在比较值的时候，得到不正确的结果。如果存储的数据范围超过decimal的范围，那么建议将数据拆成整数和小数并分开存储。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如果存储的字符串长度几乎相等，则使用char定长字符串类型。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>8【强制】varchar是可变长字符串，不预先分配存储空间，长度不要超过5000个字符，如果存储长度大于此值，则应定义字段类型为text，独立出来一张表，用主键来对应，避免影响其他字段的索引效率。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>9【强制】表必备三字段：id、create_time、update_time。说明：其中id必为主键，类型为bigint unsigned、单表时自增、步长为1。create_time和update_time的类型均为date_time。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>表的命名最好遵循“业务名称_表的作用”原则。[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>14【推荐】当单表行数超过500万或者单表容量超过2GB时，才推荐分库分表。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：如果预计三年后的数据量无法达到这个级别，请不要在创建表时就分库分表。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>设置合适的字符存储长度，不但可以节约数据库表空间和索引存储，更重要的是能够提升检索速度。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>其中无符号值可以避免误存负数，且扩大了数据的表示范围。</p>
</blockquote>
</blockquote>
<h3 id="◆-5-2-索引规约" tabindex="-1"><a class="header-anchor" href="#◆-5-2-索引规约" aria-hidden="true">#</a> ◆ 5.2 索引规约</h3>
<blockquote>
<blockquote>
<p>1【强制】业务上具有唯一特性的字段，即使是多个字段的组合，也必须建成唯一索引。说明：不要以为唯一索引影响了insert速度，这个速度损耗可以忽略，但会明显提高查找速度；另外，即使在应用层做了非常完善的校验控制，只要没有唯一索引，根据墨菲定律，就必然有脏数据产生。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2【强制】超过三个表禁止join。需要join的字段，数据类型必须绝对一致；当多表关联查询时，保证被关联的字段需要有索引。说明：即使双表join，也要注意表索引、SQL性能。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3【强制】在varchar字段上建立索引时，必须指定索引长度，没必要对全字段建立索引，根据实际文本区分度决定索引长度即可。说明：索引的长度与区分度是一对矛盾体，一般对于字符串类型数据，长度为20的索引，区分度会高达90%以上，可以使用count(distinct left(列名, 索引长度))/count(*)的区分度来确定。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4【强制】页面搜索严禁左模糊或者全模糊，如果需要，那么请通过搜索引擎来解决。说明：索引文件具有B-Tree的最左前缀匹配特性，如果左边的值未确定，那么无法使用此索引。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>5【推荐】如果有order by的场景，请注意利用索引的有序性。order by最后的字段是组合索引的一部分，并且放在索引组合顺序的最后，避免出现file_sort的情况，影响查询性能。[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6【推荐】利用覆盖索引进行查询操作，避免回表。说明：如果想知道一本书的第11章是什么标题，我们有必要翻开第11章对应的那一页吗？只要浏览一下目录就好，这个目录就起到覆盖索引的作用。正例：能够建立索引的种类分为主键索引、唯一索引、普通索引3种，而覆盖索引只是查询的一种效果，用explain的结果，extra列会出现“using index”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7【推荐】利用延迟关联或者子查询优化超多分页场景。说明：MySQL并不是跳过offset行，而是取offset+N行，然后返回放弃前offset行，返回N行。当offset特别大的时候，效率会非常低，要么控制返回的总页数，要么对超过特定阈值的页数进行SQL改写。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>SQL性能优化的目标：至少达到range级别，要求是ref级别，最好是consts级别。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：1）consts级别是指单表中最多只有一个匹配行（主键或者唯一索引），在优化阶段即可读取到数据。2）ref级别是指使用普通的索引（normal index）。3）range级别是指对索引进行范围检索。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：explain表的结果，type=index，索引物理文件全扫描，速度非常慢，index级别比range级别还低，与全表扫描相比是小巫见大巫。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当建组合索引时，区分度最高的在最左边。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：如果存在非等号和等号混合判断条件，那么在建组合索引时，请把等号条件的列前置。如：where c&gt;? and d=? ，即使c的区分度更高，也必须把d放在索引的最前列，即建立组合索引idx_d_c。</p>
</blockquote>
</blockquote>
<h3 id="◆-5-3-sql语句" tabindex="-1"><a class="header-anchor" href="#◆-5-3-sql语句" aria-hidden="true">#</a> ◆ 5.3 SQL语句</h3>
<blockquote>
<blockquote>
<p>1【强制】不要使用count(列名)或count(常量)来替代count(<em>)，count(</em>)是SQL92定义的标准统计行数的语法，与数据库无关，与NULL和非NULL无关。说明：count(*)会统计值为NULL的行，而count(列名)不会统计此列值为NULL的行。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不要使用count(列名)或count(常量)来替代count(<em>)，count(</em>)是SQL92定义的标准统计行数的语法，与数据库无关，与NULL和非NULL无关。说明：count(*)会统计值为NULL的行，而count(列名)不会统计此列值为NULL的行。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2【强制】count(distinct column) 计算该列除NULL外的不重复行数。注意，count(distinct column1, column2)，如果其中一列全为NULL，那么即使另一列有不同的值，也返回为0。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3【强制】当某一列的值全为NULL时，count(column)的返回结果为0，但sum(column)的返回结果为NULL，因此使用sum()时需注意避免NPE问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>正例：可以使用如下方式避免sum的NPE问题：SELECT IFNULL(SUM (column), 0) FROM table;</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4【强制】使用ISNULL()判断是否为NULL值。说明：NULL与任何值的直接比较都为NULL。1）NULL&lt;&gt;NULL的返回结果是NULL，而不是false。2）NULL=NULL的返回结果是NULL，而不是true。3）NULL&lt;&gt;1的返回结果是NULL，而不是true。反例：在SQL语句中，如果在null前换行，则会降低可读性。select * from table where column1 is null and column3 is not null; 而ISNULL(column)是一个整体，简捷易懂。从性能数据上分析，ISNULL(column)的执行效率更高一些。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6【强制】不得使用外键与级联，一切外键概念必须在应用层解决。说明：以学生和成绩的关系为例，学生表中的student_id是主键，成绩表中的student_id为外键。如果更新学生表中的student_id，则同时触发成绩表中的student_id更新，即为级联更新。外键与级联更新适用于单机低并发，不适合分布式、高并发集群；级联更新是强阻塞，存在数据库更新风暴的风险；外键影响数据库的插入速度。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7【强制】禁止使用存储过程，存储过程难以调试和扩展，更没有移植性。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>8【强制】当订正数据（特别是删除或修改记录操作）时，要先select，避免出现误删除，确认无误才能执行更新语句。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>11【推荐】in操作能避免则避免，若实在避免不了，则需要仔细评估in后面的集合元素数量，控制在1000之内。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>12【参考】如果有国际化需要，那么所有的字符存储与表示，均以UTF-8编码，注意字符统计函数的区别。说明：SELECT LENGTH(&quot;轻松工作&quot;)；返回为12。SELECT CHARACTER_LENGTH(&quot;轻松工作&quot;)；返回为4。如果需要存储表情，那么选择utf8mb4进行存储，注意它与UTF-8编码的区别。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>13【参考】TRUNCATE TABLE比DELETE速度快，且使用的系统和事务日志资源少，但TRUNCATE无事务且不触发trigger，有可能造成事故，故不建议在开发代码中使用此语句。说明：TRUNCATE TABLE在功能上与不带WHERE子句的DELETE语句相同。</p>
</blockquote>
</blockquote>
<h3 id="◆-5-4-orm映射" tabindex="-1"><a class="header-anchor" href="#◆-5-4-orm映射" aria-hidden="true">#</a> ◆ 5.4 ORM映射</h3>
<blockquote>
<blockquote>
<p>【强制】在表查询中，一律不要使用 * 作为查询的字段列表，需要哪些字段必须明确写明。说明：）增加查询分析器解析成本。2）增减字段容易与resultMap配置不一致。3）多余字段增加网络开销，尤其是text类型的字段。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6【强制】不允许直接将HashMap与Hashtable作为查询结果集的输出。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>反例：某工程师为避免写一个result  Mapxxx /result Map，直接使用HashTable接收数据库返回结果，结果由于数据库版本不一样，出现日常把bigint转成Long值，而线上把bigint解析成BigInteger的现象，导致线上出现问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7【强制】更新数据表记录时，必须同时更新记录对应的修改时间，即update_time字段值为当前时间。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当执行SQL时，不要更新无改动的字段，一是容易出错；二是效率低；三是增加binlog存储。</p>
</blockquote>
</blockquote>
<h3 id="◆-6-1-应用分层" tabindex="-1"><a class="header-anchor" href="#◆-6-1-应用分层" aria-hidden="true">#</a> ◆ 6.1 应用分层</h3>
<blockquote>
<blockquote>
<p>3【参考】分层领域模型规约。1）DO（Data Object）：与数据库表结构一一对应，通过DAO层向上传输数据源对象。2）DTO（Data Transfer Object）：数据传输对象，Service层或Manager层向外传输的对象。3）BO（Business Object）：业务对象，可以由Service层输出的封装业务逻辑的对象。4）Query：数据查询对象，各层接收上层的查询请求。注意，【强制】如果超过2个参数的查询封装，则禁止使用Map类传输。5）VO（View Object）：显示层对象，通常是Web层向模板渲染引擎层传输的对象。</p>
</blockquote>
</blockquote>
<h3 id="◆-6-2-二方库依赖" tabindex="-1"><a class="header-anchor" href="#◆-6-2-二方库依赖" aria-hidden="true">#</a> ◆ 6.2 二方库依赖</h3>
<blockquote>
<blockquote>
<p>1【强制】定义GAV遵从以下规则：1）GroupID格式：com.{公司/BU }.业务线.[子业务线]，最多4级。</p>
</blockquote>
</blockquote>
<h3 id="◆-6-3-服务器" tabindex="-1"><a class="header-anchor" href="#◆-6-3-服务器" aria-hidden="true">#</a> ◆ 6.3 服务器</h3>
<blockquote>
<blockquote>
<p>1【推荐】高并发服务器建议调小TCP协议的time_wait超时时间。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：操作系统默认240s后，才会关闭处于time_wait状态的连接。在高并发访问场景下，服务器端会因为处于time_wait的连接数过多，而无法建立新的连接，所以需要在服务器上调小此等待值。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2【推荐】调大服务器所支持的最大文件句柄数，即fd（全称：FileDescriptor）。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说明：主流操作系统的设计是将TCP/UDP连接采用与文件一样的方式管理，即一个连接对应一个fd。主流的Linux服务器默认支持最大的fd数量为1024，当并发连接数很大时，很容易因为fd不足而出现&quot;open toomany files&quot;错误，导致新的连接无法建立。建议将Linux服务器所支持的最大句柄数调高数倍（与服务器的内存数量相关）。</p>
</blockquote>
</blockquote>
<h2 id="◆-第7章-设计规约" tabindex="-1"><a class="header-anchor" href="#◆-第7章-设计规约" aria-hidden="true">#</a> ◆ 第7章 设计规约</h2>
<blockquote>
<blockquote>
<p>在需求分析阶段，如果与系统交互的User超过1类，并且相关的User Case超过5个，那么使用用例图来表达结构化需求会更加清晰。</p>
</blockquote>
</blockquote>
<h3 id="◆-附录-专有名词" tabindex="-1"><a class="header-anchor" href="#◆-附录-专有名词" aria-hidden="true">#</a> ◆ 附录 专有名词</h3>
<blockquote>
<blockquote>
<ol>
<li>CAS（Compare And Swap）：解决多线程并行情况下使用锁造成性能损耗的一种机制，这是硬件实现的原子操作。CAS操作包含三个操作数：内存位置、预期原值和新值。如果内存位置的值与预期原值相匹配，那么处理器会自动将该位置值更新为新值，否则处理器不做任何操作。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="2">
<li>DO（Data Object）：在阿里巴巴集团内部专指与数据库表一一对应的POJO类。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="3">
<li>GAV（GroupId、ArtifactId、Version）：Maven坐标，用来唯一标识jar包。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="6">
<li>ORM（Object Relation Mapping）：对象关系映射，对象领域模型与底层数据之间的转换，本文泛指iBATIS、MyBatis等框架。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="7">
<li>POJO（Plain Ordinary Java Object）：在本手册中，POJO专指只有setter/getter/toString的简单类，包括DO/DTO/BO/VO等。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="8">
<li>AO（Application Object）：在阿里巴巴集团内部专指Application Object，即在Service层上，极为贴近业务的复用代码。</li>
</ol>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<ol start="9">
<li>NPE（java.lang.NullPointerException）：空指针异常。</li>
</ol>
</blockquote>
</blockquote>
</div></template>


