<template><div><p>手机淘宝运营攻略：开店、装修、运营、推广、内容营销（第2版）
近水思鱼</p>
<p>◆ 序言</p>
<blockquote>
<blockquote>
<p>现在社会不缺乏理想，而缺乏去脚踏实地完成的人。每天空喊口号，学习只学到皮毛就谈战略，这样在互联网中是站不住脚的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>聚焦。放弃成千上百的好点子，把点子集中在一个焦点上！就像我们一直做一个萌萌的互联网坚果。我遇到很多人给我们提建议：你可以这样做坚果，也可以去投资做一点别的，很多对于别人来说很好的创意，我们都否决了，坚持做一个“三只松鼠”，做一个我们熟悉的领域和产品！</p>
</blockquote>
</blockquote>
<p>◆ 1.2 淘宝开店的前期准备</p>
<blockquote>
<blockquote>
<p>如何在淘宝网上开一家独树一帜、标新立异、稳赚人气的网店，便成了许多自由创业者重点考虑的问题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>创业有时会很顺利，有时也会充满艰难和风险。但不管怎样，对于一个创业者来说，首先要自信，要相信自己的选择是正确的，相信自己能成功，这是创业的原动力。而积极向上的态度，会让人迫不及待地尝试新事物，催人不断奋进。聪明的人会利用积极的心态把压力转化为动力，而愚蠢的人只会把消极的心态作为逃避的借口。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>今天要想从网上赚出大钱来很难，但请相信在网上赚钱一定会是明天的趋势。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>经营网店最忌讳的就是急功近利，完全从表面看市场。有些人看到流行什么就马上经营什么，经营了才知道不是那么回事，于是，干一行怨一行，被市场牵着鼻子走，最后感叹生意难做，一事无成。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不管做哪一行，每一次的成功都是在付出无数辛苦和努力的基础上开出的花朵。要想成功，必须踏踏实实地奋斗。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>网上开店其实和开实体店一样，千万不要以为自己的店一开起来，摆上东西就可以在家等着收钱了；也不要看别人的店开得很好，就以为自己的店开起来生意也会不错。任何一个新开的店，都会经历一个长短不一的生意暗淡期，都会面临各种困难、遇到各种挫折。罗马城不是一天建成的，所以一定要多一份耐心，想想开店自己会得到什么、失去什么，最好和最坏的结果是什么。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>创业需要冲动，但冲动之后更需要冷静。这种冷静理性的心态主要表现在对创业项目可行性的分析要全面、理性、严谨。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>网上创业者大部分是首次创业，一般没有创业经验，创业所依据的基本上是通过在书本和各种媒体上所获得的知识与信息，在创业之前只能停留在理论分析上，无法深入地了解其他项目。所以，创业者需要尽可能把问题考虑周全，这样才能从容面对接下来的一切。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在家里时，父母会安排好一切，在单位时，领导会分配工作任务，而创业时，业务经营和发展方向等一系列问题都需要自己来决定。虽然遇到困难时可以咨询父母和朋友，但他们的帮助和建议只能起辅助作用，更多的时候还是要根据自己的独立分析和决策来解决问题。所以，创业者一定要有独立打拼的心理准备，不要一出现困难就手忙脚乱。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>面对比自己强的竞争对手，要学会欣赏，并从中学习他人的长处，而不是嫉妒、中伤。嫉妒和中伤只会更加突显自己的不自信，是对自己极大的不肯定。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>承认自己的不足、欣赏并从内心佩服自己的竞争对手是需要勇气的，但也是成大事者必备的心态。看到别人的优点，承认自己的不足和缺点，才能明白为什么别人比自己强，只有这样才能不断进步，不断超越自己。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>做任何事情都不能靠一时的激情和冲动，做好一个网店也同样是这个道理。要做就要做到有始有终，如果遇到一点挫折就怀疑自己的选择，丧失了克服困难的勇气，那么什么事情都做不好。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>现实中就有不少人因为无法坚持下去，不知道逆境中如何鼓励自己，从而丧失了原本很好的创业机会。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>据调查，48%的卖家只努力1个月，看不见成效就不干了；25%的卖家努力2个月没有成功就不干了；15%的卖家努力3个月没有成功就不干了；只有12%的卖家在3个月之后还一直在努力，而80%的大卖家是从这12%的人中产生的。如果你能坚持不懈，成为这12%中的一员，就有很大的成功机会。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6.传真机、打印机生意做大做广之后，就需要经常和供货商及顾客签订合同，这也是对双方权利的法律保障。因为距离的原因，传真机就成了必要的选择。传真机一般用于收发合同等，而打印机则可用于打印一些电子文档。目前市场上有不少的打印、传真、复印一体机，价格从高到低一应俱全，各个卖家可以根据自己的具体情况来选用</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7.扫描仪有时候，供货商提供的产品资料及图片为印刷品，无法直接传输到电脑里，这时卖家就需要用扫描仪把图片扫描下来，再上传到网店上</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>什么是网店的市场定位？</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>第一，所谓市场定位，就是根据目标市场上同类产品的竞争状况，针对顾客对该类产品某些特征或属性的重视程度，并结合自身的情况，为自己的店铺及所经营的商品塑造有针对性的、强有力的、与众不同的鲜明个性或形象，并将这种个性或形象生动有力地传递给目标顾客，求得顾客的认同，从而使顾客在众多网店中一眼就能看到自己的店铺。其实质是使自己的网店与其他的网店严格区分开来，并且使顾客能够明显地感觉和认识到这种差异，从而在顾客心目中形成特殊的地位。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>第二，网上店铺的市场定位，就是卖家根据自己所拥有的各种资源，通过分析、取舍、组合，明确自己的网店与其他网店相比最具价值的发展方向，然后根据所选中的产品或服务的属性，以及竞争对手的状况，确立自己的店铺在网络市场上的位置，并利用顾客对店铺相关产品或服务的重视程度，为店铺及所经营的商品塑造与众不同的形象，以区别于其他竞争对手。其实质就是对目标顾客群体的细分。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一个经营服装的网店，把目标顾客群体确定为中青年女性，但是这个群体的需求差异性仍然很大，有的人是为了追求时髦，不惜高价购买潮流服装；有的人是为了显示自己的身份和社会地位而购买高价、高质且雅致的服装；有的人是由于收入低或追求朴素，购买大众化的服装。市场细分后，每个市场就变得小而具体，细分市场的规模、特点显而易见。顾客的需求清晰了，卖家就可以根据不同的商品制定不同的市场营销组合策略，从而适应顾客不断变化的需求。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有句成语叫“潜移默化”，客户看到的多了，就会受到影响，也就慢慢认可了你的理念。营销的目的就是让品牌深入人心，打动人的心灵。这个看似重复的宣传文案，却发挥着威力无穷的力量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在开店之前需要做的前期市场定位准备工作有产品定位、市场考察、货源渠道、店铺设计</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.产品定位做任何生意，你首先要明白自己要销售什么。是否对要销售的产品有一个好的定位是决定营销成败的关键。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在进行产品定位时，你需要了解这类产品是否真实可靠，质量是否足够完善，在目前的市场上是否拥有活跃的交易份额。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.市场考察</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对产品进行了定位后，就需要进行市场考察。多跑几个实体市场，多进几家虚拟网店观察，看这类产品所占的市场份额有多大，是否达到市场饱和，还有无空缺，交易量如何，利润还有无上升的空间。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>分析消费群体，看他们主要偏重于购买哪类消费品，要懂得跟上时代的潮流。分析同行竞争者，观察其营销模式，看是否值得借鉴或如何加以改进。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>只有大的人流量才能提高客流量，而客流量决定了产品的成交量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝店市场定位的原则</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在进行市场定位时应该明确以下几个原则</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.类目选择</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一般选择类目的原则有以下几个。第一，有资源优势。比如，开服装店，自己家附近有大型衣帽批发市场；卖茶叶，家人、朋友有茶叶货源；卖玩具，自己家族里有玩具工厂等。第二，看好行业前景。比如几年前开始普及的智能手机、智能设备等。第三，兴趣爱好。比如因为喜欢陶瓷器皿，有这个兴趣，于是开始经营陶瓷器皿店铺。这种情况下如果一开始生意很艰难，但因为有兴趣而不容易放弃，以后就会慢慢好起来。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.从消费者的角度来思考</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>几乎没有人可以一次就把定位定得很准确，所以需要创业者在经营过程中不断思考，及时调整和优化自己店铺的定位。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.店铺定位的几种方式</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）价格牌。利用低价来跑量，实现薄利多销的销售目的；或是通过低价吸引顾客，从而拉动高价商品的销售。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）专业牌。利用自己的专业知识博取顾客的信任，比如一些新技术产品或者操作复杂的产品。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）特色牌。店里的产品可以做到“人无我有，人有我优”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（4）增值牌。提供超出买家期望的增值服务，所售商品有较大的附加价值，或者在淘宝平台上为其他卖家提供服务。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（5）感情牌。感情是需要时间和耐心来维护的。现在有很多母婴用品店的店主就是刚生完宝宝的妈妈，这样的掌柜在和买家交流时，容易引起共鸣，有利于交易的达成。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>网店市场定位的起点是网民的消费心理，只要把握了网民的消费心理，并借助恰当的手段把这一定位传递给目标网民即可。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>准确的市场定位是要掌握已存在于顾客心中的想法，打开顾客的联想之门，使自己提供的商品在顾客心目中占据有利的地位。</p>
</blockquote>
</blockquote>
<p>◆ 2.1 店铺的设置与优化</p>
<blockquote>
<blockquote>
<p>买家对店铺的认同感越强，就越容易成为意向客户</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.1.1 选择店铺风格店铺风格主要是指店铺的模板元素和配色基调，它决定了店铺给人的直观印象，所以选择一个合适的店铺风格很重要。选择店铺风格的具体操作如下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.1.4 为店铺添加背景音乐当买家进入店铺时，如果能听到优美的音乐，那么可能会增加买家对店铺的好感。下面介绍如何为网店添加背景音乐，具体操作步骤如下。[插图]打开“淘宝卖家服务市场”，在搜索框里输入“店铺音乐服务”，单击“搜索”按钮，</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.1.5 给店铺添加计数器新手卖家在开店的过程中想了解自己店铺每天的具体流量数，可以为店铺添加一个流量计数器。下面介绍添加51La统计器的具体操作流程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>打开“店铺管理”|“宝贝分类管理”，在“宝贝分类管理”中单击“添加手工分类”按钮，新建分类“51La”，并单击“添加图片”，将复制的代码粘贴在相应位置，单击“确定”按钮</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>执行操作后，51La流量统计方法就申请成功了</p>
</blockquote>
</blockquote>
<p>◆ 2.3 商品管理</p>
<blockquote>
<blockquote>
<p>[插图]</p>
</blockquote>
</blockquote>
<p>◆ 2.4 交易管理</p>
<blockquote>
<blockquote>
<p>2.4.2 扫描发货卖家可以通过千牛客户端，利用手机的自带摄像头来进行快递单号的扫描录入，具体操作步骤如下。在千牛官网上下载千牛手机客户端，登录千牛，在“工作台”中单击“订单管理”按钮进入其界面，切换至“待发货”选项卡。选择相应订单，单击“发货”按钮，选择发货方式及物流公司，并单击“扫描单号”按钮，将摄像头对准快递单号进行扫描，即可完成扫描发货</p>
</blockquote>
</blockquote>
<p>◆ 3.1 店铺装修常识</p>
<blockquote>
<blockquote>
<p>3.对空间使用率的考量对于一个实体店铺来说，空间产出率是衡量一个店铺效益的重要标准，因而每一个商家都在尽力增加有限空间产品的数量，并尽力使得每件商品都能和顾客有接触。网络零售的优势之一就是互联网突破了时间和空间的限制，但是虚拟空间范围的无限性和空间利用的有效性却是相对的，特别是对于网络零售业者来说，只有用户能接触到的位置才是有价值的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>卖家一方面需要提升网店空间的使用率，让单一的网店容纳更多的产品；另一方面则需要在产品之间的关联性和产品的分类优化上下功夫，给予消费者最大的选购空间和最简便的购物流程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>现今的淘宝网店分为两种，一种是旺铺，一种是普通店铺。而最近淘宝又将旺铺分为了标准版旺铺和创业扶植版旺铺。无论其类型怎么发展变化，其网店装修设计的方向和内容是基本一致的，都需要进行店标、店招、促销模板、公告、宝贝页模板等方面的设计。</p>
</blockquote>
</blockquote>
<p>◆ 3.5 布局模块管理</p>
<blockquote>
<blockquote>
<p>图片轮播是淘宝网标准版店铺才有的功能，如果能够找到可以图片轮播的代码，将代码粘贴放在自定义内容区，一样可以达到图片轮播的效果。</p>
</blockquote>
</blockquote>
<p>◆ 4.1 拍摄商品照片的构图基础</p>
<blockquote>
<blockquote>
<p>4.1.1 突出主体</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在用手机拍摄商品时，对同一物体从不同的拍摄角度进行拍摄时，得到的照片效果是截然不同的。不同的拍摄角度将带来不同的感受，有时选择独特的视点可以将普通的商品以更新鲜、别致的方式展示出来。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>使用俯视角度拍摄会将更完整、更全面的商品面貌拍摄下来，会引导欣赏者以俯视的角度避开前景欣赏画面</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>仰视角度拍摄商品则能够表现场景的空间效果，使主体对象在简洁的背景中更加突出和醒目</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4.1.3 透视关系</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>透视关系是在日常生活中无所不在的一种视觉现象，距离物体越近物体就显得越大，离得越远物体就显得越小，在远处形成一个相交的点，这个点在透视学中被称之为“消失点”，呈现在手机摄影画面上也是如此。透视关系的这一原理常用在拍摄装修、室外用品等店铺图片中</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4.1.4 比例关系</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当手机镜头的画面中只有一个孤零零的商品时，它的大小以及体积就会变得难以确定了。此时，拍摄者需要借助一个大家都熟知的物体作为参照才能更好地展示它的大小以及所占空间范围</p>
</blockquote>
</blockquote>
<p>◆ 4.2 快速上手的商品拍摄技巧</p>
<blockquote>
<blockquote>
<p>4.2.1 画面色彩平衡</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在使用手机拍摄商品照片的过程中，你可以通过变换拍摄角度，并站在不同的位置拉开与被拍摄物体的距离，或者为手机改装不同的拓展镜头，以达到正确的画面色彩平衡。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>使用暖色调拍摄的手机淘宝商品图，可以给欣赏者带来一种温暖和愉快的心情。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4.2.2 光线与色彩</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>光线与色彩是所有彩色画都需要考虑的基础点和关键点，也是画家作画时经常遇到问题的地方。在手机淘宝商品摄影中，如何运用光线与色彩也是摄影者必须考虑的关键问题。例如，强烈的直射光产生的光照效果比较大，可能会导致被拍摄物体的细节和本质色彩的丢失。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>直射光对于色彩的反差变化和光影的明暗对比效果有很好的突出作用。当采用散射光作为光线环境时，使用手机拍摄的作品更容易得到理想的色彩效果</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>掌握拍摄时机</p>
</blockquote>
</blockquote>
<p>◆ 4.3 手机摄影的注意事项</p>
<blockquote>
<blockquote>
<p>避免使用数码变焦</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>很多智能手机没有光学变焦器件，在拍摄过程中基本上都是利用软件来进行变焦的，因此变焦越多获得的图像质量就越糟糕</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>为了保证得到高质量的原始图像，有经验的用户绝不会随意使用手机的数码变焦功能。当然，对影像质量有要求的用户可以为手机额外配置一个光学变焦镜头，依靠光学镜头结构来实现变焦效果。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>调节最佳分辨率和宽高比</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>很多智能手机的屏幕尺寸比较小，但是分辨率却很高，这样造成的直接后果就是照片内容显示得非常小，甚至小到看不清楚</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在使用手机拍摄商品时，分辨率和宽高比参数并不是越大越好，而要根据实际的屏幕尺寸和镜头性能来调节最佳分辨率和宽高比。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>通过单击调整对焦和曝光</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在使用手机拍摄商品照片时，用户可以用手指单击一下屏幕，即可看到屏幕上出现了一个小方框，它可以对其所框住的景物进行自动对焦和自动测光</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>用户在使用手机拍照时，可以使用以下方法调整照片的亮度：单击镜头中的较亮物体进行测光，则照片会变得更暗；单击镜头中的较暗物体进行测光，照片会变得更亮；单击镜头中的中性色（通常表现为灰色）进行测光，则照片上的明暗关系就比较接近人眼所看到的感觉。</p>
</blockquote>
</blockquote>
<p>◆ 4.4 用APP拍出宝贝靓照</p>
<blockquote>
<blockquote>
<p>用APP拍出宝贝靓照</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>“魅拍”APP支持普通拍照、触屏速拍和声控拍照等多种拍照方式，同时集特效滤镜、智能美颜、趣味拼图和夜景模式等功能于一体，功能十分强大，对于拍摄淘宝商品照片有很大的帮助。</p>
</blockquote>
</blockquote>
<p>◆ 4.5 用修图APP快速美化店铺图片</p>
<blockquote>
<blockquote>
<p>用户可以单击美图秀秀APP界面下面的美颜效果缩览图，根据需要或者自身喜好应用不同类型的美颜处理，包括自然、红润、白皙、甜美、梦幻、柔嫩、清新、冷艳、清晰、阳光等</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>美图秀秀还可以对淘宝模特照片进行人像美容处理，打造完美面孔，如通过对人物照片进行磨皮、亮白处理，快速呈现如玉肌肤。美图秀秀APP中的瘦脸、增大眼睛、去黑眼圈、亮眼等功能，可在细节上对手机淘宝店铺的模特照片进行修饰。</p>
</blockquote>
</blockquote>
<p>◆ 第5章 手机淘宝店铺运营管理</p>
<blockquote>
<blockquote>
<p>手机淘宝店铺运营管理</p>
</blockquote>
</blockquote>
<p>◆ 5.1 数据的采集和分析</p>
<blockquote>
<blockquote>
<p>数据的采集和分析</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>要进行数据的采集与分析，就需要明确数据采集与分析的流程，要了解数据对于卖家的用途是什么，是为了提高营业额还是为了了解店铺的被关注度，进而把这些问题的解答转化为一个数据采集和分析的初步方案</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>数据采集可以分成两部分来做，一部分是数据提取，另一部分是数据整理。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>数据分析同样可以分成两部分来做，一部分是数据挖掘，另一部分是数据分析。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）数据挖掘：是透过企业内储存的大量资料，以找出不同的客户，分析客户的喜好。通过分析企业原有数据，做出归纳性的推理，从中挖掘出潜在的需求模式。（2）数据分析：数据分析可帮助人们做出判断，以便采取适当行动。数据分析是组织有目的地收集数据、分析数据，使之成为信息的过程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于多数淘宝卖家而言，在进行数据分析时都会先采集几个重要的数据：访客数、浏览量、跳失率、人均浏览量、平均停留时长（秒）、收藏量、浏览回头客、浏览回头率、平均访问深度等。这些数据通过数据分析软件“生意参谋”，可以非常直观地展现给卖家</p>
</blockquote>
</blockquote>
<p>◆ 5.2 数据分析推广工具</p>
<blockquote>
<blockquote>
<p>数据分析推广工具</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在淘宝中，最常用的数据分析软件是生意参谋、淘宝指数等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>经营分析页面有流量分析、商品分析、交易分析、营销推广4大块。流量分析。流量分析提供了全店流量的概况、流量的来源和去向、来访的访客时段地域等特征分析、店铺装修的趋势和页面单击分布分析。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>通过流量分析，卖家可以快速盘清流量的来龙去脉，识别访客特征的同时，了解访客在店铺页面上的单击行为，从而评估卖家店铺的引流、装修等健康度，帮助卖家更好地进行流量管理和转化。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>商品分析提供了店铺所有商品的详细效果数据，包括5大功能模块：商品概况、商品效果、异常商品、分类分析、采购进货</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>选词助手。选词助手从PC和无线两个终端，分别提供给店铺引流的店外搜索关键词、反映用户需求的店内搜索关键词、根据所选关键词相关的行业内搜索关键词，同时提供了这些关键词的搜索热度、引导效果等</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>选词助手可以帮助卖家做到以下几点：快速盘清搜索来源的关键词，验证和调整关键词的投放策略；了解访客在店内的搜索行为，明确访客的精准需求；通过行业搜索词的拓展，帮助卖家找到更多适合店铺的可拓展关键词。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>行业排行。行业排行目前包含六大类：热销商品榜、流量商品榜、热销店铺榜、流量店铺榜、热门搜索词、飙升搜索词</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>行业排行为卖家提供了专属的店铺排行与宝贝排行，并为PC端与无线端分别创建了独立榜单，让榜单更加细分精准。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>单品分析。单品分析能够帮助卖家分析引流来源的访客质量、关键词的转化效果、来源商品贡献，让卖家清楚引流的来源效果；能够让卖家清楚商品的变化趋势，掌握规律，迎合变化，提高转化率；能够让卖家了解商品访客的潜在需求特征，迎合需求，让访客买得舒心；还能够量化搭配商品效果，帮助卖家盘活店铺流量，促进访客买得更多</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>阿里指数是一个专注于电商平台市场动向的数据分析工具，主要运用的数据指标包括每天网站浏览量、每天浏览的人次、每天新增供求产品数、新增公司数和产品数这5项</p>
</blockquote>
</blockquote>
<p>◆ 5.3 提升手机淘宝转化的方法</p>
<blockquote>
<blockquote>
<p>提升手机淘宝转化的方法</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机淘宝店铺的运营，简单来看，就是流量和转化这两件事。目前，很多店铺的流量都得到了提升，但手机淘宝的转化却成了大多卖家头疼的问题，下面介绍提升手机淘宝转化的方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机端顾客不像PC端那样容易看到很多产品的信息，所以一个能体现你产品特性和卖点的标题，就显得很重要。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>卖家在设置手机端的宝贝标题时，可以加入一些主要的词，也可以加入该产品的特点词。手机端并不需要像PC端那样为了搜索而抢更多的搜索热词，手机端主要是为了转化，所以加入产品的卖点元素是重点</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机搜索权重的宝贝描述强调的是加入手机详情页就可以增加权重，这里要强调的是如何优化好详情页，才能增加权重。很多店铺的卖家在做无线端的宝贝描述时，直接把PC端的手机描述导入到手机端的描述里面，直接导致了手机端宝贝描述整体过于冗长，其实手机端的宝贝描述一般做到6屏就可以了</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>很多手机淘宝的买家是不咨询客服，不长时间浏览的，他们的时间只有2～3分钟，所以卖家把握这段时间，把产品的一系列信息展示给客户，已经变得越来越重要了。目前在手机端出现了音频描述形式，显示为“听掌柜说”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机淘宝在宝贝详情的第一页只是展示了一个评价，这个评价很关键。因为很多顾客为了节省流量，直接就看这么一个评价，所以在手机端，排名第一的评价一定要做好</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>排名第一的评价需要具备的要素有以下几点：买家的旺旺的级别；产品的相关性；物流的相关性；客服的服务态度；顾客的对产品的想法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在手机端，你的客服反应时间越短，买家咨询和购买的可能性就越大。现在的千牛工作台有客服机器人，一定要应用起来。</p>
</blockquote>
</blockquote>
<p>◆ 5.4 淘宝网店的库存管理</p>
<blockquote>
<blockquote>
<p>一般来说，活动主打商品，在活动结束后，仍能保持很高的转化率，所以主打商品的数量准备多多益善。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>然后是其他热销商品，就是核心商品，应和活动主打商品尽可能关联，搭配套餐，内页推荐，手段很多种，这批核心商品，建议准备比平时多1～2个月销量的库存。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>考虑到大型活动的一些特性，建议活动当日有意识地控制在架商品数量。比如在双十二当日将在架商品数从500种降为300种，主要将那些销量不好，库存不多的商品下架。这样做的好处有如下几个。（1）降低仓库配货的难度：减少配货人员去翻冷门商品的可能性。（2）减少客户的选择面：选择不是越多越好，尤其是在很多人都有选择恐惧症的今天。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>英国科学家曾经做过一个实验，让一组人从3种巧克力里挑选一个，另一组则从17种巧克力里挑选。结果对自己选择的满意度，第一组远高于第二组。所以说，控制在架商品种类，缩小活动当日的选择面，加速客户下订单的决心，对于整个活动是很重要的一环，同时作为入口商品的关联销售是非常重要的。</p>
</blockquote>
</blockquote>
<p>◆ 5.5 维护老客户远胜开发新客户</p>
<blockquote>
<blockquote>
<p>淘宝店铺必须引入关系营销中的老客户维护策略，真正认识到老客户是店铺最重要的一部分财富，才是店铺长久发展的必由之路。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这就是著名的“漏斗原理”。今天流失10个，同时又来10个，从表面上看销售业绩没有受到任何影响，而实际上为争取这些新客户所花费的宣传、促销的成本显然要比维护老客户昂贵得多，从投资回报程度的角度考虑是非常不经济的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>留住老客户还会使宣传推广成本大幅度降低。发展一个新客户的投入是巩固一个老客户的5～9倍。在许多情况下，即使争取到一个新客户，也要经过一段时间才有可能发生消费行为。因此，确保老客户的再次消费是降低销售成本和节省时间的最好方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>老客户营销的方式有以下几种。1.老客户维护常用途径和办法维护老客户，要明确客户需求，积极满足客户需求。（1）发展会员法：普通会员和VIP会员，不同的会员享受不同的购物折扣，会员可分为付费会员和非付费会员。（2）购物积分法：这是维护老客户普遍应用的方法。根据每次所购商品的价值赠送不等的积分，积分累加可以享受不等的购物优惠或者是积分兑换等。（3）返送购物券法：购物时据购物商品的情况赠送不同价值的购物券，供客户下次购物使用。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.特殊买家特殊对待根据“二八原则”，公司利润的80%是由20%的客户创造的，哈佛商业杂志的一篇研究报告指出：多次光顾的买家比初次登门的客户可多为企业带来20%～80%的利润。所以善于经营的卖家要根据买家本身的价值和利润来对待买家，并密切关注高价值的买家，保证他们可以获得应得的优质服务和待遇，使他们成为店铺的忠诚客户。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>联促网为商家提供了一个独创的维护老客户的平台。通过一个小小的联促积分卡的号码就把买家和卖家绑在一起，买家登录联促网第一时间就会看到卖家的信息，比如，热销的产品、新上架的商品、促销的商品以及卖家要和自己的老客户要说的话等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.建立客户数据库</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>4.利用无线微淘</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>横空出世的微淘，被誉为淘宝系的微博。很多卖家看着不少微淘大号，已有几百万的粉丝，一定很着急，那么中小卖家，在品牌知名度不高的情况下，应该怎样练好内功，运营好自己的微淘呢？（1）用内容留住粉丝。微淘广播中关注你的粉丝，主要分为两种：老客户和对你内容有依赖的消费者。这时，卖家需清楚自己微淘的定位，是做个推销产品的促销员，还是行业的“公知”？对于微淘粉丝，大都是处于20～35岁之间的“80后”“90后”来说，他们厌倦了赤裸裸的推销，所以微淘扮演促销员的角色肯定不讨好，相反，做“公知”的角色，推送粉丝喜爱的广播内容，更容易建立信任的桥梁，拉近买卖双方的距离。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）内容精包装。广播内容要亲和自然，不能随便网上找来文案，复制粘贴就了事，这样的广播内容，会让消费者觉得不被尊重，所以摘抄来的广播内容一定要经过简单的编辑加工</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）给内容定个位。广播内容其实不难找，网上有很多相关的内容可以搜索到。但是要思考的是，怎样的广播内容能引起消费者的共鸣。这需要挖掘，消费者需要什么。比如卖家具的卖家，能想到关注微淘的粉丝，一定是最近家里装修的，而且大多数是女性。因此，广播内容应该以家装知识、家居生活贴士小窍门为主，可以拉近粉丝的距离，而且还能获得粉丝的信任。所以，建议广播内容多跟产品产生相关性。再比如卖女装的，可以分享材质、如何搭配；卖化妆品的可以推送护肤技巧、保养诀窍等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（4）把控推送时间巧引关注。其实，随着阿里系的APP享受免费流量政策出来以后，阿里系的几个移动端的APP成为很多买家的“福音”。因而买家更愿意享受免费的流量，使用这些APP，这也给微淘注入了新的生机。然而，有些卖家会问，为什么在这些APP上发布了内容，却依然增粉不多？其实，把控好推送内容的时间很重要。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>微淘广播推送的时间，尽量选择碎片化的时间点。推荐几个时间点：7:30，是多数消费者在上班路上，等公交或者坐公交的时间；11:30，是消费者吃午饭前，等餐排队的时间；12:30，是消费者吃完午饭，休息的时间；17:30，是消费者下班等公交，或者在公交车上的时间；19:00，是消费者吃完晚饭，休息的时间；23:00，是消费者临睡前，在床上玩手机的时间。</p>
</blockquote>
</blockquote>
<p>◆ 6.1 千牛客户端的操作</p>
<blockquote>
<blockquote>
<p>千牛客户端分流的功能，能帮助卖家解决因客服子账号外出时仅登录千牛手机版，不能正常接待买家的烦恼。开启手机分流后，当参与分流的客服子账号仅登录千牛手机版时，等同于登录了千牛电脑版，买家流量会正常分配到这些客服账号上，客服只用手机也能正常接客。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>登录千牛电脑版，单击“[插图]”切换至工作台模式，在此界面的右下角，单击“插件市场”按钮，切换至“设置”选项卡，弹出“插件中心”对话框，单击“工具栏插件”下方的“客服管理”按钮，开启“旺旺分流”插件，如图6-34所示。</p>
</blockquote>
</blockquote>
<p>◆ 6.3 客服必备的知识和能力</p>
<blockquote>
<blockquote>
<p>了解不同的物流及其运作方式。一般为邮寄：邮寄分为平邮（国内普通包裹）、快邮（国内快递包裹）和EMS。快递：快递分为航空快递包裹和汽运快递包裹。货运：货运分汽运和铁路运输等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不同物流方式的价格：了解如何计价，以及报价的还价空间还有多大等问题。不同物流方式的速度。不同物流方式的联系方式：在手边准备一份各个物流公司的电话，同时了解如何查询各个物流方式的网点情况。不同物流方式应如何办理查询。不同物流方式的包裹撤回、地址更改、状态查询、保价、问题件退回、代收货款、索赔的处理等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>常用网址和信息的掌握：快递公司联系方式、邮政编码、邮费查询、汇款方式、批发方式等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>客服促成交易的技巧主要有以下几点。1.利用害怕买不到的心理人们常对越是得不到、买不到的东西，越想得到它、买到它。客服可利用这种“怕买不到”的心理，来促成订单达成。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.利用希望快速发货的心理大多数买家希望在付款后，商品能够立马被寄出。所以，当买家还在最后犹豫中时，可以说：“亲，如果真的喜欢就赶紧拍下吧，快递公司的人再过10分钟就要来了，如果现在拍下，可以今天就帮你寄出去哦！”这对于用网银或支付宝在线支付的买家尤为有效。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.采用“二选一”的技巧店里的品种非常多，买家很难抉择的时候，客服可以通过“二选一”的技巧，帮助买家抉择。譬如，可以说：“请问您需要第2款还是第16款？”或是说：“请问需要寄哪种快递给您？”这种问话技巧，只要买家选中一个，其实就是你帮他拿主意，下决心购买了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>5.巧妙反问，促成交易当买家问到某种产品，不巧正好没有时，就得运用反问来促成订单达成。比如说，买家问：“这款有金色的吗？”这时，客服不应回答没有，而应该反问道：“不好意思，金色已经没有了，不过我们有银色、黑色、紫色、蓝色的，在这几种颜色里，您比较喜欢哪一种呢？”</p>
</blockquote>
</blockquote>
<p>◆ 7.2 淘宝直播：边看可边买，所见即所得</p>
<blockquote>
<blockquote>
<p>淘宝直播（又称淘宝达人）就是一个以网红内容为主的社交电商平台</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于那些没有开店只是帮助商家推荐商品的淘宝达人而言，也可以从商家处获得佣金收入。在这种互联网电商模式下，直播视频内容充当了流量入口，为商家或自己的店铺提供推广渠道。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝直播的视频内容规范如下。1.视频时长最长不要超过5分钟（视频大小要控制在1000 M以内）。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.内容要求（1）淘宝直播目前开放的内容方向：服饰、美妆、母婴、运动户外、美食，数码、教育等。需要注意的是，以下内容不能出现在视频中，如图7-37所示。[插图]</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）淘宝直播的标题规范：标题最多可以输入22个字，必须清晰地表达视频的主题，可以采用简单的分享字样，或者注明是一个实用教程</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）封面图。由于系统会自动将标题放置在封面图片上，因此商家不用再在图片上写其他文字内容</p>
</blockquote>
</blockquote>
<p>◆ 7.3 有好货：千人千面的流量展示新平台</p>
<blockquote>
<blockquote>
<p>有好货：千人千面的流量展示新平台</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝“有好货”的优势分析“有好货”的位置非常不错，在手机淘宝端，其位于头条和直播入口的下方，“淘抢购”的右侧，地理优势明显要好于“必买清单”。再者，“有好货”主要为单品展示，商家可以运用专业的文案，并搭配白底或者实景的产品图片，即可吸引精准的买家单击</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在淘宝的电脑端页面中，“有好货”可以获得较大的展示面积，有利于商家为商品引流</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>“有好货”的报名规则需要注意的是，“有好货”不是发布后就会一直保留在上面，系统每隔一段时间都会排除一些质量不佳的选品和图片。因此，在入驻“有好货”平台前，商家必须先了解其报名规则。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]产品定位以精致为主：“有好货”的商品定位也比较简单，并不追求爆款，而目标人群主要是那些追求生活品质的消费者，为他们推荐一些平常难以注意到的精品</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]商品图片的基本要求：在“有好货”平台上，商品的图片展示很重要，如图7-49所示。对于淘宝等电商平台来说，消费者能看到最多的就是商品图片，因此商家一定要保证图片清晰真实，而且要有质感、无“牛皮癣”，当然最好还是自己亲自来拍摄图片内容，这样不但可以避免纠纷还能突出真实感。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]产品的质量需要得到保障：商家发布到“有好货”平台上的商品必须提供质量保障</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]导购内容的范围要求：主要包括单品推荐理由和产品介绍，以及使用方法、购物知识、使用心得、品牌故事和资讯等内容</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有好货”的基本商品调性对于电商企业来说，“有好货”为其带来了一个不错的内容流量入口，是提高商品销量的重要渠道，应该好好运用。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>商家可以从国外找一些口碑好、品质好、个性强且在国内比较少见的品牌或者商品</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>商家还需要注意以下类型商品不符合“有好货”的调性要求：经常出现在各大促销平台中的品牌及商品。在线下非常热门的品牌及款式。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>“有好货”平台上不能出现高仿、明星同款、大牌仿款、山寨货等类型的商品，即商品外观、名称与大牌类似或雷同</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>假货商品不能发布在有好货平台上。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>普通网络红人款商品，如图7-55所示，也不能出现在“有好货”平台。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>价格低廉、外观粗糙、品质感差的商品。品牌比较集中或单一的品类，如奶粉、尿不湿等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如何提升商品在“有好货”上的曝光率。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.封面图片规格“有好货”的封面图片一般为尺寸不小于500×500的正方形，推荐尺寸为1080×1080。另外，封面图片还需要满足以下要求。一致性：封面图片中出现的商品要和标题、推荐理由以及宝贝详情页面中出售的商品要完全一致</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>背景要求：封面图片的背景要干净整洁，可以采用白色背景或者场景图，同时应突出主体，在构图上要尽量完整饱满，以及有较高的清晰度</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无“牛皮癣”：封面图片上不能出现水印、Logo以及其他多余文字，最好不要用拼接的图片。数量与颜色：除了套装类商品外，一般单张封面图片上只能出现一个商品主体，而且对于有多种颜色的商品也只能挑选其中的一种颜色。模特要求：对于服饰类需要使用模特照片的商品来说，通常只能出现一个模特人物，而且最好不要使用全身照片。注意：情侣装和亲子装不适用此要求。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>拍摄角度：在拍摄商品照片时，要选一个可以体现商品全貌、特点以及功能的最佳角度，最好能让用户一眼就看出这是什么商品。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>“有好货”的标题文案要求如下。内容要求：标题中可以包括品牌名称、商品产地以及品类名称，但一定要与实物商品完全一致。拒绝抄袭：切不可照抄其他商家在店铺中的原标题。用词要求：在标题中使用形容词时，注意要控制在3个词以内。同时，标题中不能出现商品的货号、规格、重量，以及包邮、满减、清仓、特价等促销词汇。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>注意数量：标题上最好不要出现商品的售卖数量字样，如5个、10双等，避免商家的促销活动前后售卖SKU（Stock Keeping Unit，库存量单位）有变化，对买家造成误导。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在“有好货”的“百科”栏目中，集中了不少对买家有用的生活常识和技巧，商家可以通过图文内容巧妙地将商品融入其中，这样不但能快速吸引买家关注，还可以为商品带来不错的流量</p>
</blockquote>
</blockquote>
<p>◆ 8.1 淘宝达人推广</p>
<blockquote>
<blockquote>
<p>淘宝达人推广</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于淘宝商家和品牌商来说，淘宝达人无疑为他们提供了一个不可多得的推广渠道，特别是在引流方面，达人可以借助淘宝头条、淘宝直播、有好货、爱逛街、必买清单等多个渠道进行内容营销，引爆商品流量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>介绍一些淘宝达人的必备条件：时尚，有品位。热爱淘宝，喜欢购物。有很丰富的购物经验，可以让人信服你的选货眼光。具备一定的品牌知识，可以找到一些稀缺的品牌好货。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>宝达人有哪些特点。（1）内容定位：对行业十分熟悉，可以生产相关的行业内容。（2）功能定位：可以运用内容的影响力和号召力，吸引大量粉丝互动。（3）结算方式：主要采用CPS（成交付费）和CPC（展现付费）两种方式。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在手机淘宝的首页，除了淘宝头条、淘宝直播、有好货、爱逛街、必买清单等内容电商模块外，淘宝达人还可以借助每日好店、微淘、“问大家”社区等获得不错的精准流量，同时对消费者选购物品来说也更加方便</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝达人有这么多好处，那么商家应该如何与他们合作来推广自己的商品或品牌呢？（1）改变自身思维。对于传统电商来说，一定要学会用互联网思维来卖货，抛弃以往的单一导购渠道推广，而将精力放在社交导购的场景化渠道上。（2）加强员工培养。对于淘宝店铺的运营人员来说，以往大家用得最多的就是搜索引擎推广和直通车了，如今，内容运营平台和数据分析工具成为了商家推广必不可少的新渠道，这些都是员工需要学习和加强的方面。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）培养自己的达人。对于拥有一定规模的店铺来说，可以自己培养达人，或者招聘一些达人，以及与达人签约形成强强联合，为达人们提供活动策划、活动推广、活动图片、活动内容等一系列服务，让他们协助完成店铺的推广目标。（4）优化策划和文案。很多大型淘宝店铺都拥有自己的策划部门和文案部门，此时可以让他们针对淘宝达人平台，采集一些优质的内容、图片、视频等进行分析，并且制定一些符合达人宣传的内容。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（5）加强客服服务。最后，针对淘宝达人专注的行业领域，客服人员也需要加强产品的相关认知，做好充分的准备来接待和应答买家们的针对性问题。另外，客服人员还可以借用达人的内容来引导客户，和他们进行深度交流，并分析他们的属性和关注特点，为了推荐更加合适的产品，让他们感受到店铺的“靠谱”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如何成为淘宝大V达人</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>如果你要申请成为大V达人认证，则还需要发布5篇内容，并积累100个粉丝，而且质量分需要超过20</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>不管成为哪个行业的淘宝达人，都需要具备一定的创作能力，写一些自己的故事和经历，而且内容还要和行业相关</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝达人的内容创造绝不是简单的复制和粘贴，这其中需要花费很大的精力，而且如今淘宝的认证审核也非常严格，因此大家在打造达人的过程中一定要注重细节，不管是名称和头像设置，还是内容的编辑，都必须提前做好规划。要善于利用互联网的极致思维来打造达人，将生活、工作、电商中的每一个细节都做到极致，有了好的基础才能真正成就爆款。</p>
</blockquote>
</blockquote>
<p>◆ 8.2 手机淘宝内部推广</p>
<blockquote>
<blockquote>
<p>手机淘宝的内部推广方式主要有以下几种。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线会员卡</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线会员卡是手机淘宝端最重要的一款会员关系管理工具，目前面向部分卖家开放。对于商家来说，无线会员卡可以当作店铺权益的一个载体集合，同时还拥有手机淘宝的高流量入口，可以极大地增加店铺的用户黏性</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>互动营销工具互动营销工具主要包括分享有礼和手机海报两个工具</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机海报手机海报是一个免费的推广神器，卖家可以一键将海报分享到微淘、朋友圈等社交平台。依次进入“我是卖家&gt;营销中心&gt;手机营销专区”页面，在互动营销工具的“手机海报”选项区中单击“马上创建”按钮进入其页面，卖家可以在此选择相应的模板来制作手机海报</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>店铺收藏淘宝的收藏人气是淘宝人气宝贝权重提升的重要因素，是一个店铺热度的衡量标准，人气宝贝的排名制度——人气宝贝＝本期售出＋累计售出＋评价次数＋浏览量＋收藏人数——也需要看收藏的人数，因此提升淘宝的收藏人数是让店铺人气翻倍的快捷途径。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.收藏的好处具体来说，收藏的好处有以下几点。（1）收藏数的多少可以动摇一个人的购买欲望。（2）在同类店铺中，收藏数高的店铺往往曝光量要比其他同行多。（3）在同类商品中，收藏数高的商品往往比收藏低的商品卖得更火热。（4）买家搜索宝贝的时候，人气搜索显示的就是收藏数最多的宝贝。（5）收藏数越多，产品在同类产品中排列的位置就越靠前。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（6）宝贝或者店铺的收藏数越多，也会带动买家收藏店铺的其他宝贝。（7）收藏数与信誉一样重要，能让买家感觉真实可信。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.增加收藏的方法增加收藏的方法主要有以下3种。（1）与买家交流时，主动邀请他们收藏。（2）装修店铺时，在醒目位置放置收藏按钮，并写上鼓励买家收藏的文字。（3）与其他网店相互收藏。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘小铺“淘小铺”是阿里无线战略的重要步骤，是手机淘宝的一款应用工具，它可以让买家完全凭借手机完成从买家端到卖家端的操作。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.淘宝推出淘小铺的原因与中心化流量分配的PC时代相比，移动互联网时代，人与人之间的距离更近，以人为中心的消费场景更加多元化、个性化。作为商家在无线端的运营工具，“淘小铺”承载着多维度连接买家与卖家的作用，为卖家，尤其是淘宝平台上的中小卖家，自定义流量入口。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这些淘宝中小卖家的现状是：在线上，他们获取流量的能力远远小于平台上的大卖家；在线下，他们又无法与银泰这样的实体去抢流量。即便有很强的流量输入，由于生产规模等限制，他们的流量承接能力也比较差，但他们在产品品质、服务上却能做到更加用心，实现与买家一对一的交流。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>“淘小铺”旨在帮助这些淘宝中小卖家以更低的成本在无线端与用户互动、交易。这种互动是精准的，交易也能实现完整的闭环。而且以二维码的形式，卖家可以通过社群方式对店铺进行精准的推广、引流。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.淘小铺优势帮助卖家进行无线化升级，是“淘小铺”的核心价值之一。另外，在无线端，为卖家提供更多的通道，帮助其与买家连接、互动，也是“淘小铺”的价值所在。“淘小铺”可以帮助卖家随时随地做生意，随时随地和买家进行沟通，实现真正意义上的无线化，即基于无线这个平台，有更多连接卖家和买家的业务模式。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>具体优势有以下几点。（1）随时随地发布商品，操作订单，接收消息，及时了解店铺数据。（2）移动管理店铺，全套订单操作。（3）多样化无线营销工具，实时数据查看分析。（4）所有的淘宝开店经营全部都可以在“淘小铺”进行。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝将大力推广“淘小铺”第一，在推广资源方面，天天特价、海抢购、淘金币等渠道将推出“淘小铺”专场，为其推广、引流，在微信传播特别开通了“淘小铺”店铺码。第二，在资金支持方面，蚂蚁金服将为“淘小铺”提供一整套的资金解决方案，降低商家的经营门槛。第三，在货源支持方面，天猫供销平台超一万家KA（KA即Key Account，重点客户）将与“淘小铺”合作，让更多“淘小铺”卖家零成本拿到天猫品牌商的货源。</p>
</blockquote>
</blockquote>
<p>◆ 8.4 手机淘宝付费推广</p>
<blockquote>
<blockquote>
<p>钻石展位就是指淘宝内部页面的广告，主要也是通过竞价方式，让你的广告展示在淘宝首页或其他页面中，是按CPM（展示）计费的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一般PC端的淘宝首页焦点图最低千次展现价格是7元</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>PC端淘宝首焦图右侧banner最低千次展现价格是3元</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线端的淘宝首页焦点图最低千次展现价格是5元</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.无线端钻展流量效果好的时段根据淘宝移动用户上网行为的数据来看，移动用户比PC互联网用户早上上网的时间更早且晚上持续的时间更晚，那么无线资源位的投放恰恰能把传统PC端的抄底流量发挥出最大的价值。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>卖家可以通过百度统计工具研究网民上网的时间分布，以找到最佳的无线端钻展时段。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>狭义的淘宝SEO即淘宝搜索引擎优化，是指通过优化店铺宝贝标题、类目、上下架时间等来获取较好的排名，从而获取淘宝搜索流量的一种新型技术。广义的淘宝SEO是指除去淘宝搜索引擎优化外，还包括一淘搜索优化、类目优化、淘宝活动优化等，是最大限度地吸取淘宝站内的免费流量，从而销售宝贝的一种技巧。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>标题关键词，就是设置宝贝的标题时必须有一些搜索热词，当然这里讲的是和搜索有关联性的标题关键词。一般卖家想展示什么词，怎么把产品的主要特点说出来，客户常搜索的关键词组合是什么，这些都需要时间去做数据分析。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机淘宝上最能提升搜索权重转化率的就是搜索转化率。通过搜索的关键词，进入店铺达成交易的比率越高，权重就会越大，排名一般就会靠前一些。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>比如，如果买家搜索关键词“单肩包女”，单击进入这个宝贝，然后成交，那么这个转化率对于“单肩包女”这个词的权重提升是相当有好处的。如果买家搜索“单肩包女韩版”这个词，进入这个店铺，然后成交，那么，这个转化率除了对“单肩包女韩版”这个词的权重有提升之外，对于“单肩包女”这个词的权重也是有提升的，因为“单肩包女韩版”这个词里包含了“单肩包女”这个词。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>5.手机成交量不管你是从什么渠道，用什么方式引来的流量，只要你的手机淘宝的成交量高，你的综合排名就会高，并且在同等纬度下，你在一些特定关键词的搜索中也有权重。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>6.手机淘宝店铺的流量比手机淘宝店铺获取的流量越多，店铺的排名在同纬度情况下，比其他店铺的排名会更靠前</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>7.手机广告投放量一个店铺的手机直通车和手机钻展等投放量越多，手机淘宝搜索的排名会更靠前，所以手机广告的投放量也算一个影响权重的因素。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>8.手机广告投放的转化比当一个店铺在手机直通车和手机钻展上推广的转化越高，相对来说，比其他同纬度的店铺排名会更靠前。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>9.店铺DSR评分目前，淘宝产品搜索排序中，整个权重已经开始向店铺DSR评分倾斜，店铺DSR评分已经成为了重要的权重因子，从而引导将卖家们的营销重心从量向质转移， DSR评分作为卖家衡量店铺健康的因素从来都不可忽视，让卖家直观认识到经营的缺陷</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>对于每个卖家而言，店铺动态评分（DSR评分）需要一直保持飘红的状态，任何一项变绿了都不是好事。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>小卡片：预防性的道歉。附上小卡片，大致内容是：“如果因为快递等原因让您感到不满，请多多谅解，并联系我们的客服，我们一定会给您最满意的解决方案；如果满意，请给我们五分好评，联系我们的客服，将赠送10元优惠劵”。预防中差评的同时，还能引导没有评分买家的习惯，并且促进二次购买。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>意外小礼品：减轻买家不满情绪。给买家小惊喜这种行为可以很大程度削减买家可能已存在的不满，礼品无须很贵重，主要是一份心意的体现</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2015年，淘宝推出了很多扶持金牌卖家的政策，其中店铺的搜索加权和活动报名优先等实用的政策对金牌卖家影响很大</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>11.产品的条形码产品的条形码在PC端和手机端都增加了权重。淘宝将针对条形码准确且有码率超过50%的卖家，给予专门手机端活动等资源奖励，有码且准确的商品也将获得搜索流量加权。扫码购是一个很好的活动平台，也是一个制作爆款的好方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>店铺的宝贝活跃度每个店铺都有很多商品，每个商品代表一个活跃值，而没有成交、搜索、转化的产品会拉低整个店铺的权重，所以要经常地让所有产品有一定活跃度，删除没有任何流量和销量的产品。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘抢购活动淘抢购活动可以快速增加搜索权重，宝贝只要上了淘抢购就能看到效果</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>聚划算活动搜索聚划算活动刚刚开始增加搜索权重，纯聚划算搜索权重很小，但是如果进行无线引流和成交，就会增加很大的权重</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>宝贝的卡位时间手机淘宝内，宝贝的卡位时间一般不是很长，在中午12左右和下午4点左右，还有晚上8点左右，位置最容易变动，所以，产品上下架时间的设置最好避开高峰，不然一旦挤出前三，只要后面任意落后一位，基本上转化就至少会下降10%左右，甚至更多。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝客的推广主要可以分成如下两大类。（1）拥有独立平台的专业淘宝客：这类淘宝客精通网站技术，搭建专业的平台，如淘宝客返利网站（优秀淘宝站内App、开心赚宝、惠集网、返利、QQ等）、独立博客、商品导购平台、用户分享网来吸引客户，赚取一定的佣金。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）自由的淘宝客：这类淘宝客没有固定的推广方式，不管技术还是实力都不是很雄厚，主要论坛、SNS平台，或者微博、邮件、QQ群等作为推广方式，很适合大众新手。</p>
</blockquote>
</blockquote>
<p>◆ 8.5 淘宝直通车营销</p>
<blockquote>
<blockquote>
<p>直通车是淘宝卖家们的一个非常好的引流工具，在宝贝销量比较小的情况下，自然搜索流量比较的少，想获得更多展现，及一些销量不错的宝贝想获得更多的流量，都可以使用直通车。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝直通车相当于搜索引擎的竞价排名，通过付费的方式，可以在淘宝的搜索结果页获得更好的展示机会。同搜索引擎竞价排名一样，卖家可以针对每个竞价词自由定价，并且可以看到排名位置，并按照实际被单击次数付费。每个关键词最低出价0.05元，最高出价100元，每次加价最低为0.01元。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>直通车推广的好处如果想推广一件宝贝，就需要给该宝贝设置相应的关键词、类目出价及宝贝推广标题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>直通车流量来源分为站内/站外，按类型分为关键词/定向投放，无线端也一样</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车的位置划分如下所述。1.无线站内（手机淘宝）</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>手机淘宝站内的无线直通车位置主要有以下几个。（1）明星店铺位置。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这是无线端最优质的流量，开通条件是冠级淘宝或者Tmall，必须是自有品牌，并且在直通车后台申请明星店铺通过。目前是内测，不是所有卖家都有权限。强烈建议已经开通权限的卖家朋友好好利用，它的单击率可能高达50%以上</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）关键词搜索结果列表页上的位置。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当搜索某个关键词后，搜索结果列表里，左上角带有“HOT”字样的宝贝，间隔20或者40个会出现连续的1～3个，Android端和i OS端会有些细微区别</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.无线站外（合作APP）</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>淘宝的自有流量不够用之后，开始采购外部流量，以单击付费形式销售给卖家，这就是无线的站外流量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>目前已经上线在用的媒体APP包括：暴风影音、墨迹天气、内涵段子，即将上线的还有今日头条</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>质量得分影响因素虽然直通车后台只看到一个质量得分，但真实的情况是，在关键词推广的情况下，无线直通车和PC直通车有两个不同的质量分计算方法，并且二者互相独立。这解答了很多朋友的疑惑：开通无线端直通车后，为什么单击率大幅增高，质量分却没有上涨？</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>和PC端一样，影响无线端质量得分的TOP3因素，分别如下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.文本相关性</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>和PC端相比，无线端的文本相关性更为重要。这里的文本相关性，主要指的是宝贝的创意标题。因为在直通车位置上，显示的是最多20个字的直通车创意标题，而非原标题。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>文本相关性，不仅仅是关键词要尽量在标题中出现，更是要卖点词在标题中出现。卖点词的相关性高（例如条纹衫的卖点为“经典”，只要创意标题中有“经典”，那么所有含有“经典”的关键词相关性都会较高），会极大提升该关键词的基础质量得分。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.单击率</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>任何时候，单击率都是质量得分最重要的因素，毋庸置疑。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>第一，无线端的单击率，因为众所周知的屏幕小、宝贝少的原因，单击率普遍很高。所以，在判断你的单击率是否合格的时候，标准也应该相应有所提高。这里给出作者的经验值：2%属于合格，3%以上属于优秀，如果1%以下属于很差了（声明：这是普遍意义下，某具体类目可能有所偏差）。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>第二，无线端的单击率，同时也要区分开站内和站外，还要排除掉PC端单击数据的影响。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.转化率</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>创意标题更加重要专业车手，使用直通车的创意标题，一般是作为宝贝标题的有效补充，或者是当作纯促销用语，例如“月销万件，好评如潮，不能再降了”之类的短语。而直通车的创意标题，自从无线端直通车开通后，其重要性显着提升。原因有以下3点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）PC端的创意标题，上限20个字，但是最多显示17个字，其他都被隐藏了，而无线端全部显示</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）PC端直通车位置和自然搜索结果位置区分开来，而无线端直通车位和搜索结果位是融合在一起的，但用户对此无意识。（3）无线直通车的展示规则，并不是单纯由“出价×质量分”来决定。还有一个基于创意标题相关性的过滤规则。也就是说，即使你对某关键词出高价，也可能因为你的标题相关度低而无法展现。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一直以来，匹配方式分为“精确匹配、中心词匹配、广泛匹配”3种。在PC端，这三者的差别很明显。但对于无线端，其差别正在缩小甚至消失。因为，无线端的直通车更强调精准性。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>假如，卖家购买竞价词是“武大郎烧饼”，而买家搜索词为“武大郎”。如果你匹配方式设为精准，那么PC端和无线端都一样无展现；如果匹配方式设为中心，此时竞价词的中心是产品名称“烧饼”，无法和搜索词匹配上。因此，PC端和无线端一样，都无展现。而在广泛匹配情况下，根据匹配的原则，PC端将获得展现，去淘宝搜索一下“武大郎”就能看到直通车位置上许多卖“武大郎烧饼”的宝贝；但是无线端，即使出价很高，也可能不会展现。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这是由于无线端不仅会考虑出价和质量分，它还进一步考虑了用户体验。当用户搜索“武大郎”时，一个非武大郎牌的烧饼，从搜索相关性角度来讲是很差的，因为从字面上毫无相关性。所以系统鉴定后，会放弃直通车位向该买家的展现机会，如果没有合适直通车广告，甚至会放弃此次直通车广告展现，只保留更相关的自然搜索结果，从而使得直通车宝贝无法从该关键词上获得展现。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线端的广泛匹配，可能往往会由于系统对搜索相关性提高了要求，从而退化为中心词匹配，甚至精确匹配。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线端的直通车，3种匹配方式获得展现的能力区别已经缩小，无须太在意。最简单有效的做法是全使用中心词匹配。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车出价技巧</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线端单击单价较低，原因总结起来有3个。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）为了吸引更多卖家参与无线端直通车的投放。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）在整个竞争队列中，由于一部分选手的出局，使得留下来的选手，在扣费上普遍降低。同一个竞价词下，不是所有参与出价的宝贝都显示。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）竞争的分散和不充分。简而言之，目前参与无线直通车投放的卖家还不多，竞争不充分，价格就会便宜。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车的特点是你出价高，但是扣费往往比出价低很多。所以，通用的出价建议如下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）可以大胆一点出价。这里给一个经验值供参考：无线出价＝PC端出价的150%。例如某个词在PC上出价1元，无线里就可以出1.5元。（2）关键词刚刚投放时，基础出价以比市场均价的110%为基准。精准长尾词，可以在基础上再上浮到140%。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）给自己设定一个合理的心理出价上限，热词量力而行，不要轻易超过。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（4）后续优化时，根据质量分变化来调整，质量分上涨，则价格可下调，否则上调。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车选词技巧选词，被大家熟知的常规注意事项除了有展现、单击、转化、有类目相关性、文本相关性之外，还有以下几点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.用无线端飙升词来养词</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>飙升词，指的是展现量在很短时间内突然飙升的买家搜索词。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这种词的来源往往是淘宝运营小二的人工干预，例如“626年中大促”，或者突发热点事件，例如热搜“汽车安全锤”。飙升词的优点是展现量大，竞争度小，价格便宜，非常有利于养词，能够提高质量得分。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.用标签引导词来获得展现</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在手机上打字通常很困难，所以手机淘宝用户更喜欢选择系统推荐的标签词来二次搜索。所以我们在直通车选词的时候，也要遵守这个原则来选。操作方法如下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）把你的产品词或者“产品词＋修饰词”作为起点，去手机淘宝上搜索，把它下方的所有扩展标签词记录下来</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>并作为下一次的起点来再次搜索扩展</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（2）选择另外某种属性词组合，重复上一步操作，把结果词和之前结果合并再去掉重复的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（3）重复第二步，直到词量达到200个，或者无新词可选。去掉一些属性不对的、相悖的、展现量太少的，剩下的就可以作为选词结果。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.用新版流量解析来过滤无效词</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>当确定候选词后，下一步工作是确定其有无足够的展现量，并且必须是无线端展现量。这依赖直通车后台的新版流量解析，它能告诉卖家任何竞价词的详细数据，是决策选词的必备工具。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这里会告诉卖家，这个关键词，有多少无线端的展现量。如果太少就排除掉。给一个经验阈值，一天展现量要大于100，小于该阈值的，可以认为是无效的。对于较大类目的，阈值可以适当提高一些。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车优化技巧直通车优化总结起来两件事，“换词”和“调价”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.无线端调价思路无线端调价思路和PC端一致，总结起来有以下几点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）当词不错（质量分高于7分）但是展现量不够时，不想删除的就加价。（2）当展现量够，但是单击率不够时，例如低于0.5%，降价。（3）当展现、单击都不错，但是转化能力差时，例如低于1%，降价。（4）当ROI效果好，加价，反之降价。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.无线端换词思路无线端换词思路和PC端有较大的不同，关键差别在于以下几点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）一个词在流量解析有展现量，但不一定有无线端的展现量。所以不仅要看全网展现量，更要看无线端的流量占比。（2）一个质量分高且有全网展现量的词，因为无线端直通车文本相关性的过滤规则，虽然排名不错，也不一定在你的宝贝里能获得展现。（3）所以，无线端决定一个词是否保留，取决于以下几点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>要看流量解析里词是否有无线端数据。有展现但是无线端0，果断删除。要看投放反馈数据，是否在7天内获得足够的展现量。如果一个词，价格和质量分都不错，但是一段时间后仍然无展现，就果断淘汰掉。实用规则：3天无展现的删除，7天无单击的删除，15天无成交的删除。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>无线直通车投放设置一个直通车计划，可设置点有很多。这里只强调以下几点。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>1.时间折扣这里分享一个通用的分时折扣设置建议给大家。（1）周一到周五：00:00～8:00设为30%，11:30～13:30设为120%， 19:30～22:30设为130%。（2）周六、周日：对于无线端来讲，是流量较好的时间。所以从10:00～00:00都可以设130%来获取更多流量。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>2.地域位置</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Wi-Fi的覆盖率决定了手机淘宝的流量质量，因而在直通车地域设置上，尽量选择Wi-Fi覆盖率高的大中城市。通用的地域设置建议如下。（1）关闭海外地区以及我国的港、澳、台地区。（2）关闭同行所在地，防止恶意单击。虽然手机端比起PC端更安全一些，不容易被恶意单击，但建议谨慎为好。（3）后台可设置的325个城市和地区里，结合产品特点，去掉边远地区和四五线城市。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>3.平台位置直通车后台目前没有开放“无线站内定向”“无线站外定向”的设置按钮，但如上面讲到，无线也是有定向投放的。所以要开无线直通车，通用设置建议如下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>（1）单独新建一个计划，或者清空一个原有计划。（2）平台设置，把PC端的所有可选按钮都关闭。（3）把无线端所有按钮都打开。（4）在直通车后台申请“精品宝贝”权限。必须找小二开通后，才可以投放无线站内站外定向。（5）如果遇到PC端站内关键词投放无法关闭的情况，最好找熟悉的淘宝小二申请。</p>
</blockquote>
</blockquote>
</div></template>


