<template><div><p>肾虚的男人老得快
王志国</p>
<p>◆ 第一章 没有弱男人只是肾不强</p>
<blockquote>
<blockquote>
<p>黄帝内经中提到“肾乃藏精之所，主骨生髓，开窍于耳，其华在发，五行属水”，肾一直也被称为“先天之本，生命之源”，肾精是构成人体的基本物质，与人体的新陈代谢过程有着密切的联系。《素问·上古天真论》中提到：肾脏虚，形体皆极。肾中精气是决定人的生、长、壮、老、死生命活动的主要条件，主宰着人的寿命和生命质量。肾与心、肝、脾、肺之间存在着密切的关系。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾与心：肾乃水脏，而心为火脏，心火一旦下降，肾水会相应上升，一旦肾水有病一定会殃及心脏，而心脏有疾一定也会影响肾脏，于是就会造成水火失调，心肾不交。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾与脾：肾为水，而脾为土，肾为先天之本，而脾为“后天之本”，先天的肾精需要后天脾气的滋养和培育。肾水不健康，脾土也难旺，脾随肾虚，肾衰脾竭。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾与肺：肾为水，而肺为金，金水相生，肺是肾水的上源，肺金不旺肾水难生，肾如果不纳气则会肺气短浅。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾与肝：肾为水脏，而肝为木脏，水木相生，涵养共勉。肾水充盈则肝木条达茂盛。肝木凋零则肾水空泛，二者共为母子，肾为母，肝为子。二者唇齿相依。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾调节着体内水液的代谢，决定着人的生长发育，生殖力和遗传能力。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>男人以精为本，而肾主藏精，肾好了男人才会更强壮更健康，所以男人保健以补肾为主。中医认为，人的一生，其实就是肾的一生，它主宰着并与之一起生长、发育、衰老。肾无实证，男人属阳，天性就比较爱动，活力四射，正因为如此，消耗的精气就比较多，所以男人或多或少都会肾虚，要么肾阳虚、要么肾阴虚，或者是阴阳俱虚。肾虚问题已经是男人健康的主要困扰。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾阳虚”与“肾阴虚”的区别</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾虚一般分为肾阳虚和肾阴虚，肾阳虚是指由于肾阳虚弱，温煦失职所便显出的虚寒症候。一般是因为年纪大了阳火衰弱，或者是久病所致，房事过度也会造成肾阳虚。临床表现为：面色黧或光白，腰膝酸软，身体疲倦，阳痿早泄，常见五更泄泻，完谷不化，小便清长，舌淡、苔白。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾阴虚：指由于肾阴亏损，失去滋养，虚热内生所导致的症候。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>临床表现：腰膝酸软，眩晕耳鸣，齿发脱落，男子遗精等多是由于虚劳受损或者是温热病后期，这些皆能导致肾阴虚损。</p>
</blockquote>
</blockquote>
<p>◆ 这些信号告诉你，你可能肾虚！</p>
<blockquote>
<blockquote>
<p>40岁的男人看着像老头近代衰老免疫学说认为胸腺是人体衰老最早的器官，它的萎缩是人体衰老的开始。还有学者研究发现胸腺的发育、衰退和萎缩与肾气的盛衰呈平行关系，肾不衰，胸腺的老化也会相应推迟，故调补肾气是延缓衰老的首要方法。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>衰老的速度和寿命的长短在很大程度上取决于肾气的强弱。自《内经》之后，后世医家对肾虚与衰老关系也有精辟的见解。 如，虞抟《医学正传》:“肾气盛则寿延，肾气衰则寿夭。”</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾好不好从整个人的精神状态就可以很明显的看出来。肾气充足的话，整个人都会显得神采飞扬有活力，人也显得有精神，但如果肾虚，肾气不足的话，整个人就会显得萎靡不振，胆小怕事，恐惧和人打交道，性格上会有很大的变化，甚至还会自我消沉抑郁。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>补肾对于改善人体神经体液，延缓中枢神经系统等内分泌机能减退都有很大的改善功能，同时，补肾填精还能够改善细胞能量的代谢，防治常见的老年病，如冠心病、脑血管病等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有些胖人根本不像我们想象的那样强壮，即是所谓的虚胖，走几步就喘得厉害，力气也不大，还常常腹泻便溏，这就是肾阳虚的表现，因为肾阳不足，身体水液代谢出了问题，引起水湿停滞，时间久了，体内毒素以及垃圾堆积不能排出，身体肯定会胖起来。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>为什么会连喝水都长肉呢？同样道理，肾主水，水液代谢需求仰仗肾阳的蒸腾汽化来维持体内水液代谢均衡。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>症状都表明他有严重的肾阴虚：口干舌燥、头晕耳鸣、失眠多梦、易怒暴躁、腰酸、下肢无力、小便短黄、舌苔很厚、阴茎勃起很快，初步诊断是肾阴虚引起的早泄。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>早泄主要还是肾的问题，肾藏精，肾不好自然不能正常的藏泄精液，所以治疗早泄重点是治疗肾虚。把肾阴的亏空补好，精气足了，自然就保住了性生活的时间和质量。肾阴虚病人的主要症状有腰膝酸软、口干、烦躁、手心发热等情况，这就表明了肾中津液的缺失，这个时候，不能盲目地加以治疗，如果不注意分辨阴虚和阳虚，则会加重病情，只有找到了早泄的根源，才能对其进行更好的防治。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾虚一般也分为肾阴虚和肾气虚，如果牙齿松动并伴有疼痛感，舌头瘦小薄弱，颜色较红，舌苔少或者没有舌苔，还有头晕、耳鸣等症状，一般就可以断定为肾阴虚。出现这类情况的人，往往房事过度，曾有遗精史。如果牙齿松动，牙龈淡红，舌质较淡，舌苔发白，同时懒言少语，咀嚼无力，这一般是肾气虚的症状。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>全身发黑、眼圈发黑也应该考虑是肾虚的缘故。由肾虚造成的面色黧黑，分为肾阳虚和肾精亏虚两种。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾阳虚，一般表现为面色发黑且晦暗无光，同时还有耳聋耳鸣、全身怕冷、四肢发凉、腰膝酸软等症状，小便量多且颜色清白、尿量减少、腰部以下明显水肿，舌头胖大、舌质淡嫩、舌苔发白。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾精亏虚，一般表现为面色发黑且晦暗无光，同时还有头昏耳鸣、头发脱落、牙齿松动、精神恍惚、疲倦无力、舌头发红等症状。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>中医认为，人体阳气充足，能够抵御寒冷，维持正常体温，不会产生怕冷的感觉；如果人体阳气虚弱，不能温煦机体，就会产生寒冷的感觉。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾虚会导致进入脾胃的食物得不到很好的运化，食物不能被身体吸收，人自然就会腹泻，完谷不化。身体得不到营养的吸收，肾虚会愈加严重，如果不能及时补肾，在这样的恶性循环之下，腹泻还会长年累月的出现。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>五行五脏以及五味是相对应的，五脏中的心、肝、脾、肺、肾与五味中的酸、苦、甘、辛、咸都是相对应的。所以有的人会觉得嘴里咸，有的人觉得口苦，有的人觉得口甜，而有的人觉得口酸，有的人觉得口辛，对应的，这也预示了这些人的五脏各个部分有一定的问题。咸味与肾是相对的，如果口咸，还伴有咽干口燥，头昏耳鸣、失眠多梦等现象，舌头舌质比较红，舌苔较薄，说明很有可能是肾阴虚；如果口咸，另外感觉全身倦怠、气短乏力，畏寒肢冷，腰膝冷痛、腿软无力，夜间尿频，舌头舌质淡胖，舌边有齿印，则很有可能是肾阳虚。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一般肾阳虚会引起哈欠连连的症状，同时，还会伴有面色发白无血色，夜尿增多等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>中医认为，肾为气之根，虽然呼吸的气主要在肺，但是肺气的充实是来源于肾的。当肾气充足时，肺的吸纳才能有力，呼吸才能顺畅轻松；而当肾气不足时，肺吸纳无力，呼吸就会变得越来越浅，深度不够，吸入容量变小，人体所需的气体是等量的，那么只有靠增加呼吸的频率来弥补呼吸变浅，人自然就会变得气喘吁吁了。如果这种情况得不到改善，呼吸越来越浅，肾气会越来越衰弱，人也就会越来越衰老了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾气足的人头发乌黑光亮，而肾虚的人则会出现头发脱落，枯槁早白的现象，很多“少白头”皆是由于肾虚所致。</p>
</blockquote>
</blockquote>
<p>◆ 肾的健康毁在了谁手里</p>
<blockquote>
<blockquote>
<p>伤肾的行为有很多</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>经常性的憋尿</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>各种原因造成的憋尿都严重影响着肾脏的健康。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>经常憋尿，让尿液滞留在膀胱里，尿液越积越多，膀胱胀大，膀胱壁血管被压迫，膀胱黏膜缺血，抵抗力低，就会滋生细菌及其他有毒物质，这些物质无法及时排出，就会引起膀胱炎、尿道炎等问题。继续“恶习不改”，还会引起肾盂肾炎，损害肾功能，感染前列腺炎，影响性功能。另外，人在憋尿时，肾气也相当于在“抑制”的状态，时间长了，外邪加气血的瘀滞，肾必然就会出现大问题，肾虚、肾精耗损等问题就会相继出现。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾不好了，身体就会出现失衡，因为肾是先天之本，同时，肾液主管着体内的水液，气血津液等方面的任何问题都有可能是和肾有关的。身体里的废物很多也是通过肾排出，如果肾一旦出了问题，身体里的废物就难以排出，身体自然就会出现问题了。所以憋尿不是小事，一定要注意。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>尿液的排出是一个排毒的过程，如果刻意减少饮水，导致体内水分少，肾无法通过排尿方式调节水液平衡，自然会造成毒素和废液滞留体内，损害身体。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>久坐不动的人和开车一族，应该注意运动，偶尔站起来扭扭腰、散散步。长时间开车之前要先排尿，避免路上憋尿。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]过食寒凉致肾阳虚</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>吃凉食，影响脾胃的消化，还会伤及肾阳。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>很多人运动过后就会趁着大汗淋漓饮用冰水和冰镇饮料，这样长期下去，就导致腰膝酸软、久泻不止、小便频繁清长、肢寒畏冷、抵抗力下降，严重者会身体浮肿、男子会阳痿早泄。这就是典型的肾阳虚。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>饮食上要注意：很多水果也是寒性的，不宜过多食用。夏季的水果中西瓜、香瓜、梨等，过食会引起中气不足、身体虚弱。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>中医都讲“冬吃萝卜夏吃姜，不用医生开药方”，那就是因为夏天体内其实是寒的，需要姜来温补，而冬季外面虽冷，但体内是温热的，需要萝卜来清热。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]整天坐着不爱动</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>久坐会压迫膀胱经，造成膀胱经气运行不畅，膀胱功能失常，从而引发肾功能异常，这就是“久坐伤肾”的道理。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>久坐不动的生活方式还被世界卫生组织定义为“静坐生活方式”，不仅伤肾，还使肩周炎、颈椎病、腰椎间盘突出、前列腺炎、盆腔炎及心血管疾病、糖尿病、肥胖的发生危险增加一倍，并且增加了结肠癌、高血压、骨质疏松、抑郁和焦虑的发生危险。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>中医认为，肾中藏精，肾精是维持人的生命活动的基础。如果纵欲过度，肾精损耗，人的生命之根就会受损，元神会受到紊乱，寿命也会减短。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>任何事都要适度，中国自古以来就讲究中庸之道，就好像熬汤，用文火慢慢熬才能既保持汤的营养性又避免被熬干。如果一味地性急，不仅难以保持汤汁的原味性以及营养性，水分快速蒸发，可能最后连汤都喝不了。同样的，人的欲望是无止境的，但要懂得控制，就可以做到细水长流，但是如果不加以节制的话，则会很快耗尽元气，油尽灯枯。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]滥用药物</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>我们平时吃的一些药物都是通过肾脏排出的，如果吃药不注意，剂量过大或者种类过多，都会对肾脏的结构和功能产生不良的影响，轻者浑身没劲儿、口干舌燥、不爱吃东西，重者可能会导致急性药物性间质性肾炎或肾小管坏死，甚至出现肾衰竭。尤其像索密痛片、阿司匹林还有某些抗癌药物，更是不可随便乱吃滥用。当然了，这些药物也包括壮阳药。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>养肾并不等于壮阳。肾虚除了表现为性功能方面的改变，还包含其他方面的变化，所以养肾也应从各个方面着手，不仅仅是用来解决生殖功能衰退的。另外，由于肾虚分阴虚和阳虚，壮阳是针对肾阳虚，如果你本身就是阴虚，已是“火旺”，再吃各种壮阳药物，无异于火上浇油。再者，即使吃对了药，过度补肾就会矫枉过正，补肾也得对症下药，注意适度，切不可滥用药物。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>长期盯着电脑、电视屏幕</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>人长期盯着电脑、电视屏幕会受到辐射的伤害这是众所周知的。辐射污染会影响男人的精子质量，导致生殖系统受到伤害，生育能力下降。另外，还会引起失眠、心悸，与人的循环系统免疫系统都是息息相关，分不开的。同时，对于人的视觉系统也造成不良的影响，由于人体中眼睛对电磁辐射是最为敏感的，电视尤其是电脑的辐射很容易引起视力下降、白内障等视力问题。和伤肾有什么关系呢？</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>虽然眼睛是为肝所主，但是，在五脏中，肝和肾是同源的。《黄帝内经》中说道“肾者主水，受五脏六腑之精而藏之”，由此可见，五脏六腑之精气是藏于肾的，而“五脏六腑之精气上于目”，所以说，眼睛是靠肝肾养着的，眼睛的问题其实就肝肾的问题。所以保护眼睛就是保护肝肾，损伤眼睛也就是损伤肝肾。长期盯着电脑电视屏幕，辐射对眼睛的伤害也即是对肾脏的间接损害。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>平时工作太累，长时间从事同一工作，保持同一姿势，这种情况对缓解腰部疲劳不仅无益，更会因为过长时间过度劳累而损伤肾气，导致肾精不足。事实证明，不少肾炎病人的发病就与长期过度劳累有关。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]食用芹菜过多，饮食过甜</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>经证实，芹菜是具有避孕效果的。如果每天吃芹菜，连吃一周至两周之后，精子数量很明显就会减少。这是因为肾主性与生殖，芹菜对生殖功能具有损害作用，所以，过多的食用芹菜，会对肾造成一定程度的损伤。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>过度的食用甜食会使脾旺，脾旺则会致使肾水虚弱。肾水一旦虚弱，肾主骨，骨也会受到影响，而齿为骨之余，牙齿自然也就坏了，出现牙齿松动，齿缝变宽。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾藏精，主性与生殖发育，肾中所藏的精需要吸收营养来加以补充，只有得到的营养充足，才能够维持肾的正常功能。如果减肥不当，过饥过饱，导致难以得到后天滋养，脾胃缩小，营养难以补给，先天之精得不到正常的补充，肾功能就会受到损害。一旦肾虚，性功能减退，性欲低下等问题就会随之而来。肾阳虚弱，还会出现手脚冰冷，全身怕凉的现象，同时由于肾虚，肾司二便的功能也会受到损害，尿频、夜尿增多的现象也会出现。</p>
</blockquote>
</blockquote>
<p>◆ 这些小细节教你不伤肾</p>
<blockquote>
<blockquote>
<p>这些小细节教你不伤肾</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有些人认为感冒发烧在家吃点药就好了，可是很多药物是非常刺激肾的，这样时间久了会引发慢性肾病，不容小视。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>长期服用肾毒性药物，会导致肾小管间质损害。而一些常见药里可能就含有这些药物，比如跌打丸、纯阳正气丸、冠心苏合丸等。所以肾虚的人在吃药之前，要自己查看里面的药物成分或者咨询医生，看里面有没有伤肾的药物。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>小便以后站一会</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>排尿后，应站立活动3分钟左右，再坐下。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>酒后少喝浓茶和咖啡</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>人喝酒后，90%的酒精在肝脏消化，把乙醛变成乙酸，乙酸再分解成二氧化碳和水，经过肾脏排出体外。而喝浓茶，大量的茶碱会起到利尿作用，使未分解的乙醛过早进入肾脏。而使肾脏加重负担，损害肾功能正常运转。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>成人每天不超过6 克盐，过咸过少都伤肾</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>在五味之中，咸是入肾的。肾需要咸味滋养，咸味可补充肾气，调动肾气，所以凡是咸味的食物和药物都具有补肾的作用。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>警惕这些伤肾的西药</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>氨基糖苷类抗生素：如庆大霉素、卡那霉素等。这类药物使用时间超过10天后，肾损害的发生率会明显上升。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>喹诺酮类药物：如诺氟沙星、环丙沙星、氧氟沙星等。一旦这类药物剂量偏大，便会引起尿血、间质性肾炎，严重者会导致急性肾功能衰竭。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>磺胺类药物：如复方新诺明，服药后易产生结晶而引起梗阻性肾病，出现尿血、肾绞痛，甚至急性肾衰，特别是脱水及老年病人，更易发生。因此在服用这类药物时应多饮水，并服用碳酸氢钠（小苏打）片碱化尿液，以减少对肾的损害。造影剂：是近年来应用比较广泛的药物，由它引起的急性肾功能损害也越发常见。造影剂的高渗性可加重肾缺血，也可直接对肾脏产生毒性。由于造影剂是过敏源，可引起全身性过敏反应而累及肾脏。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>利尿剂：氢氯噻嗪、呋塞米等利尿剂均有潜在的肾毒性，而大剂量间歇疗法或停药后再次服用利福平，也有可能诱发急性间质性肾炎和急性肾小管坏死等肾脏疾病，都得格外小心。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>一般情况下，剂量过大、疗程过长是用药后出现肾脏损害最主要的原因。所以，在服用伤肾药物时，首要原则就是坚持合理用药，切忌滥用药物。同时，尽量避免两种或两种以上伤肾药物的一起服用，对一些身体虚弱和情况特殊的人要根据肾功能状态调整用药剂量和疗程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>病人用药期间，应该经常做肾功能检查，这样如果有伤肾现象，可以及时发现，尽早制止。如果发现有腰酸无力、小便异常、四肢浮肿、容易疲乏、血压增高等肾病征兆，必须停药或减少用药剂量，服药期间不要嫌麻烦，要多询问医生。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>要想保护好肾，首先得保护好足，足部很容易受到寒气的侵袭。睡觉的时候应注意保暖，勿将双足置于空调和电风扇的正对面；不要赤脚在潮湿的地方长期行走。另外，足部有许多的穴位，如涌泉穴。“肾出于涌泉，涌泉者，足心也。”每晚睡前可以揉按涌泉穴，按摩涌泉穴可起到养肾固精的功效。每晚临睡前，做个足浴对肾能起到很好的养护作用。可选用熟地、黄精、山茱萸、女贞子、旱莲草、补骨脂、肉苁蓉、巴戟天等药材，每次可以选择一两种，每种150克，煎煮完毕后倒入脚盆，加入感觉稍热的水，即可进行足浴。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>冬季不要剧烈运动</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>冬三月应该尽量避免剧烈运动，避免出大汗。因为出汗会使得阳气外泄，肾气也就藏不住了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>冬三月主要就是以静为主，以藏为主的。如果冬天做了太剧烈的运动，导致大汗淋漓，就会伤肾。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>少穿紧身裤</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>人体内有很多的共生菌，有些有害，有些有利，这些共生菌都是相互制约的。如果破坏了这种平衡，就很容易对身体造成伤害。肾主性与生殖，主前后二阴，紧身裤容易导致生殖器官血液循环障碍，尤其对于男性来说，可能会导致不育。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>这是因为人体的阳气运动规律和自然界的阳气运动规律是同步的。春天的温暖有利于阳气的生，夏天的炎热有利于阳气的长，秋天的温暖有利于阳气的收，而冬天的寒冷则有利于阳气的藏。多亲近自然，有利于肾气的生长过程的循环，如果只在四季如春的人工环境中，肾气只能生，没有经历长、收、藏的阶段，肾当然就会虚弱。很显然，四季如春的人工环境是不利于人体的健康的。</p>
</blockquote>
</blockquote>
<p>◆ 第二章 会吃的男人肾气足</p>
<blockquote>
<blockquote>
<p>黑色入肾，补肾非常讲究“吃黑”，那些黑色的食物，看着没什么食欲，却对肾脏大有裨益，比如黑米、黑芝麻、黑豆等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑米是食药两用的大米，是中国古老而名贵的黑稻品种。黑米营养丰富，具有“滋阴补肾，健身暖胃，明目活血”, “清肝润肠”,“滑湿益精，补肺缓筋”等功效；可入药入膳，对头昏目眩、贫血白发、腰膝酸软、夜盲耳鸣症疗效尤佳。长期食用可延年益寿。因此被称为“补血米”“长寿米”等。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑豆则性平、味甘，高蛋白，低热量归脾、肾经。具有消肿下气、润肺除燥热、活血利水、祛风除痹、补血安神、明目健脾、补肾益阴、解毒的作用，还可以有效地缓解尿频、腰酸以及下腹部阴冷等症状，所以黑豆被称为“肾之谷”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑芝麻药食两用，具有“补肝肾，滋五脏，益精血，润肠燥”等保健功效，被视为滋补圣品。一方面是因为含有优质蛋白质和丰富的矿物质，另一方面是因为含有丰富的不饱和脂肪酸、维生素E和珍贵的芝麻素及黑色素。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑米红枣粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑豆桂圆汤</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>黑芝麻粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>枸杞黑芝麻粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>桑葚黑芝麻粥</p>
</blockquote>
</blockquote>
<p>◆ 吃对肉—哪里不足补哪里</p>
<blockquote>
<blockquote>
<p>鸭肉滋阴很出名</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>鸭肉具有“滋五脏之阴，清虚劳之热，补血行水，养胃生津，止咳息惊”等功效。《本草纲目》称鸭肉可“填骨髓、长肌肉、生津血、补五脏”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>食用鸭肉可消暑滋阴、健脾化湿、补益虚损，因此鸭肉是夏季清补之佳品，特别适合心脏病病人、癌症病人和放疗、化疗后的病人食用，还可用于阴虚失眠、肺热咳嗽、肾炎水肿、小便不利、大便干燥、低热等症。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>鸭肉忌与甲鱼、兔肉、核桃、木耳、荞麦同食。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>羊肉是温补之宝</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>羊肉含有丰富的蛋白质，具有补肾壮阳、暖中祛寒、温补气血、开胃健脾的功效。尽管吃羊肉好处多多，但不是所有的人都适宜吃的。虚劳怕冷、中气不足的人群比较适宜吃羊肉，特别是阳虚的人群，因为羊肉本身有补肾壮阳的作用，所以自古以来就被当作是壮阳的佳品。而又因为羊肉属于热性的食物，人吃了比较容易上火，所以一些急性感染性疾病的病人，如发热的病人，以及一些阴虚火旺、易口干、易上火的人吃羊肉就要注意了。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>羊肉是冬季最好的进补食材。能够补肾壮阳，温补气血，暖中祛寒，特别适合阳虚脾胃虚寒体质的人食用。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>海参味甘、咸，性温，具有补肾益精、壮阳疗痿、润燥通便的作用，凡眩晕耳鸣、腰酸乏力、梦遗滑精、小便频数的病人，都可以常吃海参来辅助治疗。据记载，海参具有壮阳、滋阴、补血、调经、养胎、利产、促孕等效用，以之治肾虚阳痿、肠燥便秘、糖尿病等，都有一定的辅助疗效。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>单吃羊肉已经具有一定的补肾效果，如果配合海参食用，则属于“强强联手”不仅效果加倍，还不会上火。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>排骨黑豆枸杞汤</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>乌鸡是有名的食疗珍禽，对于滋阴清热，补肝益肾，健脾止泻等方面都有显著的功效。《本草经疏》中说乌鸡“走肝、肾血分”，说的意思就是乌鸡入肝、肾，补血益阴。《本草再新》中提到，乌鸡“平肝祛风，除烦热，益肾养阴”，则更明确地指出了乌鸡益肾养阴的功效。</p>
</blockquote>
</blockquote>
<p>◆ 坚果、粮谷—让你顿顿都吃补肾餐</p>
<blockquote>
<blockquote>
<p>坚果、粮谷—让你顿顿都吃补肾餐</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>核桃是民间众所周知的补肾补脑佳品。中医上认为，核桃对补肾有很好的作用，能够通命门，利三焦，起到补血养气、止咳平喘、润燥通便等功效，适用于虚寒咳嗽、腰痛腰酸、阳痿遗精、须发早白、尿路结石、小便频数、大便燥结等症。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>核桃既可以用于生吃，也可熟食，或者用作药膳粥、煎汤等，</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>核桃粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>补肾固精，温肺定喘。治久病或老年人肺肾阳虚气弱，阳痿，遗精，小便频数，腰酸脚弱，咳嗽气喘。还可用于老年或体虚所致便秘。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>山药与莲子一并服用更养肾</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>山药性平，味甘，有健脾、补肺、固肾、益精之功，不管是阴虚火旺还是肾气不固导致的遗精早泄，都适合常吃多吃。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>山药莲子粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>小米最主要的功效—补脾胃</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>说到小米补虚损的功效，不仅仅体现补脾胃上面，还体现在补肾功效上，所谓“人食五谷而化精”，就是说，五谷都具有养精气，补肾气的作用，但五谷当中，数小米的补肾功效最强。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>[插图]板栗生食板栗有补肾、止血的功效。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>养成每日早晚各吃风干的生板栗5～10枚的习惯，可以达到有效预防和治疗肾虚、腰酸腿疼的目的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>生食板栗有止血的功效，可治吐血、衄血、便血等常见出血症。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>板栗排骨汤</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>材料：排骨500克，栗子250克，胡萝卜1根，姜片、盐、鸡精适量</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>板栗枸杞粥</p>
</blockquote>
</blockquote>
<p>◆ 蔬菜补肾，壮阳助性</p>
<blockquote>
<blockquote>
<p>韭菜就是有名的壮阳草，能够治疗肾阳虚引起的性功能减退等症状；大蒜不仅杀菌效果显著，还能健身补脑；豇豆则是豆中的补肾专家，补肾健脾；海带也因其泄热止水、止咳平喘等功效被称为“长寿菜”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>韭菜最适宜温补肾阳</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>韭菜中含有大量维生素，还含有丰富的膳食纤维素，每100克韭菜含1.5克纤维素，比大葱和芹菜都高，可以促进肠道蠕动、预防大肠癌的发生，同时又能减少对胆固醇的吸收，起到预防和治疗动脉硬化、冠心病等疾病的作用。但韭菜并不是多多益善，现代医学认为，有阳亢及热性病症的人不宜食用。韭菜的粗纤维较多，不易消化吸收，所以一次不能吃太多韭菜，否则大量粗纤维刺激肠壁，往往引起腹泻。最好控制在一顿100克至200克，不能超过400克。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>春韭为佳，养生全靠那股子冲味</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>初春时节的韭菜品质最佳，晚秋的次之，夏季的最差，有“春食则香，夏食则臭”之说。因此，咱们选择春季吃韭菜，不但满足养生，更满足我们的口腹之欲。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>大蒜健身强肾效果好</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>大蒜虽然味道重，但却是一味很好的保健药，不仅对于杀菌作用显著，还可以健肾补脑。从中医的角度来说，大蒜性温、味辛，入脾、胃、肺经。《随息居饮食谱》中有介绍：“生者心热，熟者甘温，除寒湿，辟阴邪，下气暖中，消谷化肉，破恶血，攻冷积。治暴泄腹痛，通关格便秘，辟秽解毒，消痞杀虫。外灸痈疽，行水止衄”。这段话中可以看出大蒜具有除寒湿、辟阴邪、下气暖中、攻冷积的功效，所以，无论是中医师还是西医师，都会把大蒜作为防治养胃的一剂良药，它能够刺激雄性激素分泌，并且增加精子数量，改善勃起功能，所以也是补肾益脑的上品。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>蒜蓉油麦菜</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>材料：大蒜30克，油麦菜300克，油、花椒、食盐、味精各适量做法：1 将大蒜洗净，切成长短相似的长条，油麦菜洗净，择断。2 置锅于火上，放入油烧至七成熟，将花椒放入油锅爆香。3 放油麦菜和大蒜煸炒至熟。4 加入食盐，味精炒熟即可。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>蒜香土豆泥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>材料：土豆500克，大蒜150克，牛奶200克，黄油50克，盐、胡椒粉少许做法：1 将土豆洗净去皮，放入锅中加入水和牛奶煮熟后将土豆捞出。2 将土豆制成泥状，加入盐和胡椒粉，拌匀。3 大蒜切末。4 炒勺上火，放入牛油，将蒜末炒香，浇在土豆泥上。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>麻酱豇豆</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>海带一直以其含碘量高为人所知的，大多数人不知道的是，除了含碘量比较高，海带还具有泄热止水、止咳平喘、去脂降压、散结抗癌等功效，具有“长寿菜”之称。从中医学角度来说，海带性寒，味咸，入肝、胃、肾三经，可补肾、益阴、壮阳。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>海带豆腐汤</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>海带冬瓜汤</p>
</blockquote>
</blockquote>
<p>◆ 水果补肾有奇效</p>
<blockquote>
<blockquote>
<p>很多我们平常吃的水果都有补肾的效果，像是荔枝、葡萄等</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>荔枝有健脾益肝、生津止渴、养血补血、理气止痛、止泻缩尿等功效，适用于病后津液不足及肾亏遗梦、脾虚泄泻等症。现代医学研究证实，荔枝可改善人体性功能，用于治疗遗精、阳痿、早泄、阴冷诸症以及肾阳虚而致腰膝酸痛、失眠健忘等症。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>银耳荔枝绿豆粥</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>葡萄具有补气血、益肝肾、生津液、强筋骨、止咳除烦、补益气血、通利小便的功效，适用于脾虚气弱、肝肾阴虚、气短乏力、腰酸腿痛、水肿、小便不利等病症。</p>
</blockquote>
</blockquote>
<p>◆ 补肾常见的中药材</p>
<blockquote>
<blockquote>
<p>补肾常见的中药材</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>冬虫夏草主要用于补肾润肺、益气生津、平衡阴阳、延缓衰老、对防癌抗癌、贫血虚弱、乙肝、提高人体的免疫力起固本作用。最适宜以食疗方式进补，每次10～15克，炖鸡、鸭肉类均宜。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>虫草炖鸭</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>何首乌味苦、甘、涩，性温，归肝、心、肾经。李时珍对何首乌的评价很高，他说何首乌能“养血益肝，固精益肾，健筋骨，为滋补良药，不寒不燥，功在地黄、天门冬诸药之上”。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>何首乌还有美容和乌发的功效。《本草纲目》说何首乌“可止心痛，益血气，黑髭发，悦颜色”。何首乌具有益精血、补肝肾作用，经常服用可使人气血充足，面色红润，容光焕发，面色无华或面色萎黄的血虚病人，常服制何首乌（深加工过的何首乌），可使面容青春久驻。</p>
</blockquote>
</blockquote>
<p>◆ 第三章 多做“小动作”补肾好轻松</p>
<blockquote>
<blockquote>
<p>10个补肾的小动作，分别为“护腰”、“吞津”、“抓耳挠腮”、“提肛”、“踮脚”、“护脚”“鸣天鼓”、“扣牙”、“面壁”、“深呼吸”</p>
</blockquote>
</blockquote>
<p>◆ 多吞津能养肾</p>
<blockquote>
<blockquote>
<p>多吞津能养肾</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>唾液中含有许多与生命活动有关的物质，都对保健养身起着很大的作用。唾液能滋养人的五脏六腑，能够促进消化吸收，生津补肾，润泽肌肤毛发，总之是对养肾健身有着极大的好处，与人体的健康长寿和养生保健是密不可分的。因此，唾液也被养生学家称为“金津玉液”，认为唾液和精血一样，都是生命的物质基础。所以，多吞津能强身健肾。那么，具体做法是怎样的呢？</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>用舌头在口腔内不停搅动，力度适中，感觉柔和舒服为佳，一般每次搅动30次左右直至口中有津液产生。如果津液还不够多，可以继续搅动，直到口中盛满，再分3到4次将津液慢慢吞下，也就是所谓的咽津。吞津可随时随地进行，建议次数越多越好。</p>
</blockquote>
</blockquote>
<p>◆ 肾不好多踮脚尖</p>
<blockquote>
<blockquote>
<p>中医认为，踮脚能补肾。脚上的一根经脉贯穿人的胸腹和腿脚，刺激肾气的活跃，同时也能刺激足太阴脾经和足厥阴肝经，对补肾都很有好处。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>因为踮脚能够起到补肾的功效。踮脚还能补肾？这是由于人少阴肾经的起点在足部，这条经脉是人体中很重要的一条经脉，它贯穿人体的胸腹和腿脚，刺激着肾气的活跃。久坐的人足部容易气血不顺，影响肾经的畅通。多做踮脚运动，就能刺激肾经的活跃，激发人体中气，以达到补肾固本的作用。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>踮脚尖的方法是：双脚并拢，抬起脚跟，脚尖着地，保持1分钟左右，再放下脚跟，反复进行几次。工作间隙，可以抬起脚跟走路，每次走上三到五分钟，休息一会儿，再反复多做几次，速度以自己感觉舒适为宜。实在是很繁忙的时候，也可以在坐着的时候踮起脚尖，保持大腿和小腿呈垂直状态，也可以在大腿上放一本书，以加大力度。常做这个动作，还有利于治疗慢性前列腺炎或前列腺肥大，有这种症状的男人一般被诊断为中气不足，往往排尿会有困难，也有尿不尽的感觉，这也是肾虚的表现，经常练习踮脚尖，有利于健身强精，小便自然就通畅了。</p>
</blockquote>
</blockquote>
<p>◆ 随手给自己推拿—鸣天鼓</p>
<blockquote>
<blockquote>
<p>肾开窍于耳，肾气足则听觉灵敏；耳通于脑，脑为髓之海，推拿鸣鼓穴可以调补肾元，强本固效，预防头晕、健忘、耳鸣等肾虚症状。</p>
</blockquote>
</blockquote>
<p>◆ 这样呼吸 暖心暖肾</p>
<blockquote>
<blockquote>
<p>呼吸是每个人每天都会做的的功课，但是大多数人都存在呼吸浅的问题，这是由于肾虚的缘故。肺主呼吸，肾主纳气，如果肾气衰弱，则呼吸困难，呼多吸少，由此可见，肾对呼吸有很大影响。同时，会呼吸也能起到养肾的作用。</p>
</blockquote>
</blockquote>
<p>◆ 第四章 在家就能做的保健</p>
<blockquote>
<blockquote>
<p>按摩腰眼：腰是肾之府</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>腰为肾之府，常做腰眼按摩，可防治中老年人因肾亏所致的慢肌劳损、腰酸背痛等症。</p>
</blockquote>
</blockquote>
<p>◆ 摩擦这六处可健肾</p>
<blockquote>
<blockquote>
<p>摩擦这六处可健肾摩擦在养生、预防疾病方面都有很好的疗效，为很多人所喜爱。摩擦以下几处可以帮助男性益精固肾，长期坚持，则效果显著。下腹部摩擦临睡前，将一只手放在脐下耻骨上小腹部位，另一只手放在腰上，然后一面按住腰，一面用手在下腹部由右向左慢慢摩擦，以自觉腹部温热感为度。摩击肾府双手掌放于同侧腰部，从上向下往返摩擦，约2分钟，以深部微热为度，或双手握拳，用双手背平面交替击打腰部。力度适中，每侧击打100次左右为宜。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>腹股沟按摩临睡前，将两手放于两侧腹股沟处（大腿根部），以掌沿斜方向轻轻按摩36次，可每周按摩数次，对增强性欲、提高精力有一定的作用。攀足固肾取仰卧位，两手从膝盖上拉到髋关节，经前腋窝线上行至头上，两手十字交叉手心向上，两脚蹬直，两手从上直线下落手向前伸，上身前弯，两手搬足心涌泉穴处，脚用力蹬直，手与脚用力相反，松手使身体恢复仰卧状。如此反复10次，或根据能力而决定次数。本法具强壮腰膝、补肾固精之效。摩揉睾丸将双手揉热，先用右手握住两睾丸，使右侧睾丸位于手掌心，左侧睾丸位于拇指、食指及中指螺纹上，然后轻轻揉动，向右向左各转30～50次，以略有酸胀感而无痛为度，然后再以左手如上法轻轻揉按。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>摩擦双耳晨起时，用指尖或螺纹面在双侧对耳轮体等耳部轻轻环形摩擦，或点压揉按，以局部微胀痛有热感为度。此法具有调和阴阳，疏通气血，健肾固精之效，为历代养生家所倡导。</p>
</blockquote>
</blockquote>
<p>◆ 体寒则肾虚 拔罐可驱寒</p>
<blockquote>
<blockquote>
<p>精气亏导致的遗精、早泄选穴：内关、关元、神门、大赫、心俞。方法：采用针灸拔罐法，先在穴位上用豪针进行轻刺激，针刺后拔罐15分钟，起罐后，再用艾条灸治5～10分钟，隔日1次， 10次为一个疗程。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>精气亏导致的阳痿选穴：肾俞、气海、关元、三阴交。方法：采用灸罐法。先拔火罐，留罐20分钟，起罐后再用艾条灸10～15分钟。每日一次。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾气衰导致的脱发白发、耳鸣眼浊选穴：涌泉穴。方法：先将穴位消毒，再用闪火法拔罐，留罐10～15分钟，每天1～4次，如果用三棱针配合放血拔罐最好。</p>
</blockquote>
</blockquote>
<p>◆ 脱发谢顶—常梳头</p>
<blockquote>
<blockquote>
<p>脱发谢顶—常梳头</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>梳子梳头法每天的早、中、晚各梳头1次，力度适中，头皮各部全部梳理1遍，每次2到3分钟，梳完头后再用木梳齿轻轻叩打头皮3到5分钟，最后再梳理一遍。如果能结合头部穴位叩打，保健效果更好。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>十指梳头法每天早中晚各梳头1次，用手指代替梳子，双手十指岔开从前额正中央，由前向后缓慢梳理；然后向两侧梳，将两鬓、额角、耳后头发发际均匀的反复梳理，梳到感觉头皮发热，头脑舒适为宜，每次2～3分钟。</p>
</blockquote>
</blockquote>
<p>◆ 肾炎尿血—补肾四药方</p>
<blockquote>
<blockquote>
<p>尿血多因火旺，但有实火与虚火之分。肾炎尿血鲜红，尿时一般都有尿道灼热感觉，多为实火；虚者多属病久不愈的慢性尿血之人，尿血淡红，尿时亦无灼热之感。前者宜吃具有清心泻火、凉血止血作用的清淡食物；后者宜吃具有滋阴降火，益气摄血作用的食品。</p>
</blockquote>
</blockquote>
<p>◆ 第六章 补肾进误区越补肾越虚</p>
<blockquote>
<blockquote>
<p>很多的人可能都认为，补肾就是壮阳，其实这样的观点是不正确的，正确的理解是补肾是补肾，人壮阳则是壮大阳具，两者是没有直接的关系的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>许多人认为，肾脏是影响性功能的最主要器官，把肾补好，才能提高性生活质量。有的病人性功能出现障碍，就认为是“肾”不行了，得赶紧补肾。其实，肾只是泌尿系统的重要器官，与性功能强弱没有直接联系，把肾补过劲了可能适得其反。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>脏及与其相关的一系列功能活</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>人的精神、骨骼、头发、牙齿等的病理变化都可能与肾有密切关系</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>肾虚不仅仅表现为性功能方面的改变，还包含着全身的一系列变化。而影响性功能的疾病很多，如糖尿病综合征、心脑血管疾病、前列腺疾病、外伤等。一个人肾脏功能再好，得了上述疾病也会或多或少影响性生活质量，而一个人只有肾病没有其他疾病则对性生活没什么影响。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>因此，那些由于心理因素出现了性功能减退的人，在吃了补肾药后，自认为性功能没问题了，于是在信心的作用下，产生了性功能改善的结果，补肾药起到了安慰剂作用。但对于那些有器质性病变的病人来说，再怎么“壮阳补肾”都不会产生什么作用，如果得不到及时正规的治疗，将会造成严重的后果。对肾的调补在人体生命活动中确实占有重要的位置，但要切记：补肾不等于壮阳，男人补肾一定要慎重。</p>
</blockquote>
</blockquote>
<p>◆ 六味地黄丸 越吃越有效？</p>
<blockquote>
<blockquote>
<p>肾阴虚的人服用六味地黄丸可能效果会比较好。舌质红、少苔或无苔、脉细数的人可能是肾阴虚，必须要注意的是，舌苔白厚的人说明体内可能有痰湿，要先清掉痰湿后再辨证看看是否能用六味地黄丸。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>中医强调人体的阴阳平衡，如果“阴虚”而“补阳”或“阳虚”而“补阴”，都会破坏人体平衡，加重病情。比如肾阴虚的人吃了金匮肾气丸就不对了，因为这个药是补阳的，适合肾阳虚的人。因此，以中药“补肾”时，一定要先辨证看“阴阳”。</p>
</blockquote>
</blockquote>
<p>◆ 多汗必然肾虚？</p>
<blockquote>
<blockquote>
<p>出汗是人体一种自然现象：外界温度太高会全身出汗；精神紧张或痛觉刺激时会手心、脚心出汗；吃了某些刺激性食物会脸上冒汗。不过，除了这三类情况，其他不该出汗的时候过多出汗都应该引起重视。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有些人特别爱出汗，觉得这一定是由肾虚引起的，吃各种补肾的药来进行调理，这种做法有一定的片面性。肾主水，肾不好自然会引起津液代谢的不平衡，容易出汗多。多汗一般也有两种情况，一种是自汗，在稍微运动之后，就会汗流浃背，这多为气虚，但不一定就是肾气虚，也有可能是心气虚，肺气虚，脾气虚或者肝气虚。老人和产后身体虚弱的女性是最容易出现这种症状的。另外一种是盗汗，入睡后，半夜或者黎明时分，胸部、背部、大腿等处出汗量较多，肾阴虚可能是造成这种现象的一个原因，但总的来说，睡着出汗，醒来汗止一般是由肾脏阴虚引起的。</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>有的人平时手心、脚心、腋窝容易出汗，这多是由于“脾胃湿蒸，旁达四肢手足”所致，一般还会伴有脾胃失调、肠胃不适等表现；每次吃饭的时候都会大汗淋漓，身体发热，这类病人多是胃火旺盛，平时应注意清淡饮食，不要吃得太油腻。还有些人额头部位老爱出汗，这一般是由于湿气太重，平时应多吃一些利水排湿的食物，比如薏米、山药等。</p>
</blockquote>
</blockquote>
<p>◆ 女人不用养肾？</p>
<blockquote>
<blockquote>
<p>肾阳虚者中，女性的比例更高。调补肾阳虚能提高女性体质，全面改善女性肾虚症状。</p>
</blockquote>
</blockquote>
<p>◆ 三、易出汗，怕冷，易腰疼，射精快是不是肾虚？阴虚还是阳虚？</p>
<blockquote>
<blockquote>
<p>明显的怕冷一定是肾阳虚。但是容易出汗是各种脏器虚都会导致的，“肺主皮毛”，肺虚更容易引起出汗。</p>
</blockquote>
</blockquote>
<p>◆ 四、男人肾虚能影响生孩子么？刚生出的孩子会体虚多病么？</p>
<blockquote>
<blockquote>
<p>肾虚是会影响生育，总体看精子质量会差一些，但是不能说明形成受精卵的那一颗就是不健康的，所以这个时候怀孕，可以要。不用追求理想状态，一定要补到多么强壮才要孩子，如果不是肾虚严重到一定程度，不会影响正常生活。</p>
</blockquote>
</blockquote>
<p>◆ 五、20岁左右的男青年肾虚怎么补？</p>
<blockquote>
<blockquote>
<p>未婚的大男孩，如果只是易疲劳、易出汗等小问题，无明显症状，建议食补调理一下即可。如有肾阴虚手脚心热、腰膝酸软等，可以吃点六味地黄丸。但如有明显症状，如记忆力下降、脱发、牙齿松动等，就应该就医，按照疾病来处理。</p>
</blockquote>
</blockquote>
</div></template>


